<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go</name>
   <tag></tag>
   <elementGuidId>a656039c-794b-473d-8b19-fe5e469d54f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Go_ACTBUT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Go_ACTBUT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>524bc720-8eec-4b05-ab77-3c6667d2b6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Go_ACTBUT</value>
      <webElementGuid>0aa4b3ee-a97d-460d-9dce-76f3479f0189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Go_ACTBUT</value>
      <webElementGuid>3dd9f959-42a6-43fc-ace8-465e0026d875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn i-icon i-icon-play-circle</value>
      <webElementGuid>6ac93d7f-f125-45de-98c7-68849435a89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/u8qTnYAD0pxsWpyxpNHvYQ3ol4V3dbjz54vuS/rDRLMTqmbrvjELG48ZLSrG1uU+qr4pPb7Rrj8=</value>
      <webElementGuid>b046891d-f234-4179-b468-fc7a24e8e467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return submitPage(this);</value>
      <webElementGuid>57611ff9-1df2-43eb-8eec-b0adebfa532e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>f94a84b3-803e-4e84-8b56-2a36d2641636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Go_ACTBUT&quot;)</value>
      <webElementGuid>ae6b0632-830a-4167-a3f2-ec32336d7e5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Go_ACTBUT']</value>
      <webElementGuid>a7eaa497-24ad-4562-972f-a6bcaf9f2a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Favourites']/button</value>
      <webElementGuid>61f8b51f-b472-426e-9142-d6e402d7ce8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/following::button[1]</value>
      <webElementGuid>1968d388-78fa-4ee2-a849-2fb9779548d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='©CNSI 2019'])[1]/preceding::button[1]</value>
      <webElementGuid>8d7b1c50-14de-4293-8a4a-edba2c11da0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'Go_ACTBUT', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>3e774fb0-f160-4d2b-8eff-9d6cb9cbd0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>5d04d187-332a-4df7-94a3-dc690fb6996e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'Go_ACTBUT' and @id = 'Go_ACTBUT' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>f0064b13-6575-4532-af8d-3be256b2af94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
