<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>e16dc67d-49e7-4c07-a3d3-d2a328b5dc4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='LoginButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30265371-a88b-491c-81ef-1e85fed7219e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginButton</value>
      <webElementGuid>19fc7b34-5250-429e-b597-cf08b7f4c255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Login_ACTBUT</value>
      <webElementGuid>6b1049c1-5c7c-4696-8bb3-49c9d28adc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/nR9JId0KUE8i2dZubRacoydUz4FLTeK2cEeF2ihCxgE=</value>
      <webElementGuid>a851dba8-0bdb-43a5-90e2-b7ffcb497ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn i-icon i-icon-circle-arrow-right pull-right</value>
      <webElementGuid>ef70fbdb-b63e-43c9-a159-79f4dfefd58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return submitPage();</value>
      <webElementGuid>dddb1947-87fc-4900-a374-34b63c1984c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>cca2089a-db8e-4d7e-8000-50fe982b3ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>ab431675-56e5-4f41-91c4-08942e2fe3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginButton&quot;)</value>
      <webElementGuid>2eb3fb01-803d-4448-93ec-d2bc65d62dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LoginButton']</value>
      <webElementGuid>145700cd-19ec-41d9-920a-797a587d69af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div[5]/div/button</value>
      <webElementGuid>1fbba041-a050-4d07-8ea6-ff38dfd87ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='evoBrix X'])[1]/preceding::button[1]</value>
      <webElementGuid>e6600a10-5c6a-461d-b5ed-617d91869373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='evoBrix X'])[2]/preceding::button[1]</value>
      <webElementGuid>395dff8d-03ac-4fbb-9217-8ac7fdb858ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>dd6246d6-5690-4749-aed5-d882943f8753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b9c87d8d-9061-4fde-8e56-128287eae5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'LoginButton' and @name = 'Login_ACTBUT' and @title = 'Login' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>2ca83096-b22c-4ea5-aedf-9bbe8a71f482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
