<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_userId</name>
   <tag></tag>
   <elementGuidId>368a33e8-77cd-4cf5-a783-33acbd1b882c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginUserID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginUserID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4dba614-5c92-45a7-9bc4-6767c3792d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94ac95da-cf8b-436a-ae2a-540bdfab882b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginUserID</value>
      <webElementGuid>2e309c64-4c8b-4044-a31f-ecbeb07c6f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userId</value>
      <webElementGuid>aa83c58d-243d-45ff-ac23-1b3729fe2f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>00f876a4-cdda-44c3-87ce-1ee47811d7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span11</value>
      <webElementGuid>4bd3813a-a6ee-45be-8d4a-fb6dc6bf5c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displaycol</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>02fee4e6-c65c-41d0-9f27-63cce1572479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>messagelabel</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>89216c44-4295-4af9-bec5-a9bf630a758c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>30f7f6d7-0084-40ac-8e5f-77ea17cd8b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>checkEnter(event)</value>
      <webElementGuid>52d14599-efc8-4c3f-8878-a1997f4c0eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>9db21926-298a-4032-82a7-77f0c27ecca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>57bf1b64-0740-4911-b281-b09dd9cf379c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginUserID&quot;)</value>
      <webElementGuid>2b27a153-4db7-45e8-9c30-88087e939f11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginUserID']</value>
      <webElementGuid>082c05cb-282f-4f31-adae-1b3c57b7d817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div[3]/div/input</value>
      <webElementGuid>2d73261b-5d10-4f99-b2e9-57b41cd5163b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>e6b58252-6f97-4f52-b89d-0cc9305aebf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loginUserID' and @name = 'userId' and @placeholder = 'User Name']</value>
      <webElementGuid>ab9036e8-395e-460a-9d31-bb675526a462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
