<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_password</name>
   <tag></tag>
   <elementGuidId>17fc46ac-fac6-4773-bccc-57e4dd6dc142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginUserPwdSSO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginUserPwdSSO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e0e0612-579c-4a50-bf2d-1ac171a6cb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0d37a25c-171a-4447-b19e-4f15bd74037f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginUserPwdSSO</value>
      <webElementGuid>cc496a0f-5d09-41be-be65-f986b12c5c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6fe5e954-d2a1-4fb4-9a07-490d27157cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>753ece02-90ab-4ac4-9a8d-9f7cc91e6c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span11</value>
      <webElementGuid>e89c67e2-bfa9-4494-9c31-182bf4a0c186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displaycol</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>784499fa-8ae1-45d2-ac85-89e3f0324f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>messagelabel</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>dcfb16cd-59d3-4c7f-a5c6-25e9f95b2450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ce25de05-023b-484b-b5c2-919aa30325b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>checkEnter(event)</value>
      <webElementGuid>c9596d68-8e4c-426a-b773-b86c791a10df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>fd426351-0769-4ed4-9819-f1335c0f1d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginUserPwdSSO&quot;)</value>
      <webElementGuid>653c4ec2-d3f4-4fee-bc53-8577a7bedaf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginUserPwdSSO']</value>
      <webElementGuid>4157349d-df29-4056-bff9-092aab89fd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div[4]/div/input</value>
      <webElementGuid>19618c07-341a-4579-8817-f5d2f4ab94ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>37abe591-4f79-4a8a-a2c4-cb211f3937bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'LoginUserPwdSSO' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>d1532322-d17a-4a9f-9fb4-30322dcff1ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
