<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_domainName</name>
   <tag></tag>
   <elementGuidId>1af2fe95-6b55-4748-818b-cbd3c0991d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginDomainNme']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginDomainNme</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78dd6f3d-fd48-4ebb-b552-4f9cc8f665d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ba71ef5-0bf6-4584-a10e-c5cba6803524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginDomainNme</value>
      <webElementGuid>40eaf11b-6be5-49ad-9114-7e4e637bd79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>domainName</value>
      <webElementGuid>5e7f4484-e40c-49f8-8b28-a1074f65f3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>06ed2b01-4a08-4ea3-9853-5267be97ee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span11</value>
      <webElementGuid>60556da4-2a8f-4a33-90ed-27cf7145a2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displaycol</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>a650f1a0-8f4b-4341-bc9e-66fbe8864a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>messagelabel</name>
      <type>Main</type>
      <value>Domain Name</value>
      <webElementGuid>191469e4-8a4e-4078-b42c-e73dff31a075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Domain Name</value>
      <webElementGuid>6c8b2398-eec8-438e-8177-defe4f028a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>checkEnter(event)</value>
      <webElementGuid>1366ef89-3cbf-483a-a169-0e18ec8b57fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>Domain Name</value>
      <webElementGuid>b40453cd-33e9-4a5e-b483-5e9654981f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>133c3634-f9e7-4ae6-852d-15a1d2f901d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginDomainNme&quot;)</value>
      <webElementGuid>1edb4018-64fc-432c-890d-737d2c1850a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginDomainNme']</value>
      <webElementGuid>c9bd500e-d1e6-420d-9f1a-f15fb23c8ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div[2]/div/input</value>
      <webElementGuid>def80f61-3f3d-4602-bc6b-b48cbe9cd3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f0366cac-d589-435b-bbb8-3305fb34e424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loginDomainNme' and @name = 'domainName' and @placeholder = 'Domain Name']</value>
      <webElementGuid>a2e70ff0-243e-4c15-afd0-5503707fcda9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
