<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>b0bb1d21-a974-4712-b246-44a0624636d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CloseButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CloseButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ad2164b-c322-4412-b6c6-892b559fd1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>ac338937-5ea6-4560-9c3b-d49e3d30f58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/FF4hnXRkBsGZriqJLKSJkVMXr1AhDqZ0zPE0w0YG2niR+PRDlOQrOvUNO6hNeHkig73Z5Pq5Gb6vTzGCzEZQbQ==</value>
      <webElementGuid>4494977d-0456-471c-bc9c-c4b41b6bd381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CloseButton_ACTBUT</value>
      <webElementGuid>423b6620-2faa-4ade-a546-d904c5880ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CloseButton</value>
      <webElementGuid>dc120f8e-c11e-474d-b7fb-0d4a5106f1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-remove</value>
      <webElementGuid>5aef9762-1079-4748-b69d-c65affd58b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return datalossConfirmationMessage('closeBtn');</value>
      <webElementGuid>75b35cf9-1c40-4a5c-b199-06b84e0f3118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>3bbd295c-37b9-42a6-a282-f03fcc20d05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>89c71aaf-30f4-4de3-b12f-453eb5f99980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CloseButton&quot;)</value>
      <webElementGuid>93b71dc4-1269-4e81-bd78-ec6d0180df22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CloseButton']</value>
      <webElementGuid>6b8ee135-ba1a-4ee7-98f5-ccab957a6b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridBtns']/div/button</value>
      <webElementGuid>234a66d8-8992-4664-9b1a-30bcef4a8439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::button[1]</value>
      <webElementGuid>62b81522-7a93-4cb2-b75d-8a73d4950569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[1]/preceding::button[1]</value>
      <webElementGuid>814c251a-ab3d-4939-895a-648568875630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShowMenu'])[1]/preceding::button[2]</value>
      <webElementGuid>d464cc35-a206-42f1-a524-18bcafdfe702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>96a03046-db5d-4fce-994a-8c51a305e2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>fa5691d5-39b2-42d7-a273-e6eeb4af0ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'CloseButton_ACTBUT' and @id = 'CloseButton' and @title = 'Close' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>8c7dfbac-869e-483f-b8ee-c7776a27ad5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
