<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>5f210209-f83d-40e8-9ed3-76ed716775e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31388373-b08c-425e-98e7-d5534d7a2a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>a0cf3f99-213c-4c47-9a5a-7b3ac7f33f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/rhR9AVu9NsRBXbjRNpmwYI6EALZdoJN8BEUd5yOvftyjqBtxeVsyD5mbvr+J33/sJ4xUdvZnoaMKUryySRHC3zj5J/WEs5T7v0XD0sVByYM/NBUr7GbaRQFoDrsg3PNzSs5LjNbp+BBfk4x/p3bRviI6nPLvUu2libIWqCot2fr8ZNJDOFSxbGD74PDL8SC0Rs0IucGZANQqQuHBDCPoQ4U5JuuGIs/lVlps116WshkWhVkmmk6AIrecWBFRb7PQJZg/xKgFkcDQPDwl/RBTNReMmTRFRWEQEFL4obZP2QOtpB5wK++bRGJFsGNVXOgMW0v2fBox0BHwwLLu6XqLHwRf8G8gTXomT6CDCbx1T00=</value>
      <webElementGuid>a6735bec-d5ac-4336-9681-535e8053b0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ok_ACTBUT</value>
      <webElementGuid>bbc7a8bf-280b-437b-918c-982c8bd1a2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ok</value>
      <webElementGuid>8e246188-1f57-4a3b-9ff9-b46685f8c363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-ok</value>
      <webElementGuid>04d77ea7-5121-494f-9fbc-56da073a53f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return submitPageMatrix(this);</value>
      <webElementGuid>9a41cd7c-e4d7-4989-a9f4-49ba9f4f5a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>4694bccf-bfe9-4493-a460-4ca7ddf33281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>225ce2fc-089d-4d48-9233-de8991851934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ok&quot;)</value>
      <webElementGuid>333d959a-6ac9-4c4d-8c6b-5666325deb24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ok']</value>
      <webElementGuid>ea251106-1032-4178-9bb4-7d6368c047f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dlgbtns']/div/button[2]</value>
      <webElementGuid>a2f3b3ef-e4ef-4c44-b84d-06197f73e8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>1995ad9b-6d48-4ca4-8137-99133f3d4c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page ID: dlgAddProcedure(Reference)'])[1]/preceding::button[1]</value>
      <webElementGuid>48c2a513-fb48-4914-ae74-50ecb790d1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>9bb81e19-1108-448b-a39f-23042171d2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e40bc7dc-449e-4aae-a841-03bcdbc22d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'ok_ACTBUT' and @id = 'ok' and @title = 'Ok' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>f9a4bb30-9fba-4173-8e54-9dcccbbb2344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
