<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Start Date_icon icon-calendar</name>
   <tag></tag>
   <elementGuidId>06ed9f2b-9cd0-4e90-bf52-6ed0f3604a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.icon-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendar_fromDate']/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cd93713a-0b39-4557-9714-0b07a7356eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-calendar</value>
      <webElementGuid>cafa2982-61ff-4210-bf73-c16cb91f8436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar_fromDate&quot;)/span[@class=&quot;add-on&quot;]/i[@class=&quot;icon icon-calendar&quot;]</value>
      <webElementGuid>ad2314be-369b-4ead-8442-42e2f503655a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendar_fromDate']/span/i</value>
      <webElementGuid>4b984eff-29e5-45bf-9f7d-35da46b79086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/span/i</value>
      <webElementGuid>a1eaf667-9139-4cf8-a476-1b8d5c785414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
