<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MUE_procedureUnits</name>
   <tag></tag>
   <elementGuidId>d59b2abd-aa47-4eff-ac85-112be640f351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#procedureUnits</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='procedureUnits']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>048bc3df-2bc2-4e6a-a626-d00d9972c737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>f3022aea-aea2-40c3-870d-c9aa31f071ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>procedureUnits</value>
      <webElementGuid>45572eb4-89a8-45f3-a30a-e6dfab82d6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>procedureUnits</value>
      <webElementGuid>97ac2fdf-4490-4bc7-8b60-e601d00b31a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab81465d-bd4b-4f9c-b009-7efe790e3bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-mini</value>
      <webElementGuid>64ecf83e-4758-4483-9563-36bf395bf8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Procedure Units</value>
      <webElementGuid>9f077263-18bc-4530-91fd-273c27e867bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>837e6129-f2ae-41d4-833c-35711cc8ea1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>procedureUnits</value>
      <webElementGuid>8df757ed-7245-461c-837d-cc993928780d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-digit</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d0e493fc-9104-49e5-855c-91f43d181290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>procedureUnits</value>
      <webElementGuid>535c7c6f-5e45-488d-96d0-11500d45b7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;procedureUnits&quot;)</value>
      <webElementGuid>738332b7-0af9-4c26-94c3-899316c721a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='procedureUnits']</value>
      <webElementGuid>87b7757c-a818-4e76-bed4-94c6b6435242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DlgWrapper']/div[2]/div[2]/div[6]/div/div/div/input</value>
      <webElementGuid>d68a1a94-9d7b-4759-8ae0-4863b717d22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>b217d400-dac4-449d-8c95-4371abff31b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'procedureUnits' and @name = 'procedureUnits' and @alt = 'procedureUnits']</value>
      <webElementGuid>229878ee-3e03-47e0-931e-7cd620d54c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
