<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Procedure Code_procedureCode</name>
   <tag></tag>
   <elementGuidId>77128cdf-a252-4861-a231-9397459dfa00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#procedureCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='procedureCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6a006e6-f818-4c51-a454-abb48faa689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>4166c5ea-7cf6-45ec-9a7c-44856b4fd73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>procedureCode</value>
      <webElementGuid>28847137-ce0e-40c7-8bc0-150565c44da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>procedureCode</value>
      <webElementGuid>f3c08f2b-f9be-4af7-9d83-e93ffbe60724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a89e77c8-bca7-430d-b15b-00315c77b1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small-CssTop</value>
      <webElementGuid>76f652ce-a657-4ff7-a292-cdd27866d0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Procedure Code</value>
      <webElementGuid>63a43330-bfad-4daf-9fa3-fb7ef7f402a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b8804464-0d0f-4666-9940-510c6ed16dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>procedureCode</value>
      <webElementGuid>73a9ce2a-1f1b-4876-955d-2cbf2076bb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>00ccce55-537a-4fa7-9bea-71f51e98ecfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c889b5c-97c9-4868-8ab5-e73bf5659252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>procedureCode_span</value>
      <webElementGuid>bb0ea52f-1d8d-48a0-b88a-97558032a4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>procedureCode Required</value>
      <webElementGuid>f9c652a0-a74b-4b97-a2f6-452b2fb1447d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;procedureCode&quot;)</value>
      <webElementGuid>01d36b61-648c-4318-86c9-77acaac5af6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='procedureCode']</value>
      <webElementGuid>0da6972c-1427-428a-a771-ce83e5bedacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DlgWrapper']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>a9e136a0-b23c-40b2-aa9e-abac905acd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e3531664-833f-4807-8456-d65b145a3fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'procedureCode' and @name = 'procedureCode' and @alt = 'procedureCode']</value>
      <webElementGuid>f9c7c2ef-e3fe-4bac-b2f1-97a781938fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
