<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Short Description_shortDescription</name>
   <tag></tag>
   <elementGuidId>f3d0bd95-0f79-4743-8433-07d25a7f13f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shortDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='shortDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>095e4610-9fba-4dea-9575-0c31c052cb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>shortDescription</value>
      <webElementGuid>2cf67389-5b59-48e0-a7b7-0e00addb2151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shortDescription</value>
      <webElementGuid>31521765-e5ae-48d6-ad1f-03a901c065a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shortDescription</value>
      <webElementGuid>857d8272-ff99-4e66-9a3b-bff4f8e776bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:setLimitTextArea(this,1000);</value>
      <webElementGuid>96fb01bf-bf53-4e28-954d-69543d51f07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:setLimitTextArea(this,999);</value>
      <webElementGuid>51a8bd6b-ea4e-4ebc-82dc-79e2eec53be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d09e04ca-4d30-426c-9f1d-9bb3e5056037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>c2b8f797-5c96-4dd6-9ecc-7f94f3d95843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea-small</value>
      <webElementGuid>7e2bfc17-7cbe-43f9-b797-0d01b3ddd716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Short Description</value>
      <webElementGuid>c3211639-ceed-45a2-9696-4a2291a740a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>89c53be2-4037-4c37-8d96-696a68bd0b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb252c60-d03e-4f1e-8119-926e7f30cae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>y</value>
      <webElementGuid>0551ca2d-cfaa-4603-b9cb-3f5dc45e57b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>5ac6664a-ae28-46ed-ab2c-bc0e9a8fb6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shortDescription&quot;)</value>
      <webElementGuid>6a8508be-2c7b-427b-8c9b-be7f1c7a3714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='shortDescription']</value>
      <webElementGuid>1c08b0b3-eb8e-40bc-8996-bba19671552a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DlgWrapper']/div[2]/div[2]/div[3]/div/div/div/textarea</value>
      <webElementGuid>6b298a66-3a33-4baf-a511-0c1975d65086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f8636032-bd74-4b58-b157-def3ee60725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@alt = 'shortDescription' and @name = 'shortDescription' and @id = 'shortDescription']</value>
      <webElementGuid>75fbdb76-a912-4626-83c6-3b831a9bfb88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
