<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Long Description_longDescription</name>
   <tag></tag>
   <elementGuidId>b4f3851a-3d48-489c-9812-047396eda3b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#longDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='longDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3a21ad03-8975-40a1-978f-8d38487aa11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>longDescription</value>
      <webElementGuid>340788ee-590d-4589-8a10-b0072817c546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>longDescription</value>
      <webElementGuid>9ce71aba-1309-4208-8468-211e750e279c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>longDescription</value>
      <webElementGuid>321a7913-8e3c-49c1-b073-1da3b162348c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:setLimitTextArea(this,4000);</value>
      <webElementGuid>45902e57-3111-41b0-a4d8-a47fea7f2112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:setLimitTextArea(this,3999);</value>
      <webElementGuid>34d1186a-91b1-475e-b5f1-e7e6837f662e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f978c8bb-fff1-4747-afa3-4fb02722b6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>2ee5e3cd-481b-4387-bf2f-397a4bdb354c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea-small</value>
      <webElementGuid>c031bde6-4d1c-4b8a-96c0-7b1720585c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Long Description</value>
      <webElementGuid>994670ca-01b4-4fbf-bb0e-c61f94ef947c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>6bc3643c-394e-4511-a062-3625c6a3972e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>307dbf68-ebc2-4988-878d-2afbb64ffdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>y</value>
      <webElementGuid>fe11db4e-c358-4ffe-96c3-a023b3f84f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>888132b7-997f-4ec2-aa06-f2cbd6eb3daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;longDescription&quot;)</value>
      <webElementGuid>0d5a3802-ac42-4e40-b132-f97bf0c8ffb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='longDescription']</value>
      <webElementGuid>e5595cd3-64c1-48ba-ab68-1ab3320745c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DlgWrapper']/div[2]/div[2]/div[5]/div/div/div/textarea</value>
      <webElementGuid>1cc73653-9470-43c8-8b04-54d6798c8389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/textarea</value>
      <webElementGuid>117a4520-7b76-464c-9277-d38f0d49bbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@alt = 'longDescription' and @name = 'longDescription' and @id = 'longDescription']</value>
      <webElementGuid>3b4e8055-b703-4407-bc00-f8b81a1a7c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
