<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Claims</name>
   <tag></tag>
   <elementGuidId>22df7bd2-095f-43a9-8088-449db4ffc898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.tabsoffline.dropdown.CLAIMS_active > a.dropdown-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='cloud_menu']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b21a3c05-8ad0-4174-b710-8d444fb7d97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>b0203aaf-5e10-40c7-b3a4-d7efde978455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Claims,press enter</value>
      <webElementGuid>c92e7ab2-4f70-45ec-92c9-2b4504a94e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>8a8729eb-3e84-400e-8b7a-46cfc4ed28ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>JavaScript:fireTabRequest()</value>
      <webElementGuid>d4516c18-c09a-44ea-8309-c92c9527824f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>11a9285f-6b0f-44b5-871d-1fcfc4169ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Claims</value>
      <webElementGuid>502209e8-f156-4906-b142-8ad0f2d8a2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cloud_menu&quot;)/li[@class=&quot;tabsoffline dropdown CLAIMS_active&quot;]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>908fb549-1beb-4b9d-ad51-84d74d4cd90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cloud_menu']/li[4]/a</value>
      <webElementGuid>528c6f10-6858-4565-b491-b44865c24329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Claims')]</value>
      <webElementGuid>93d06d5c-9a14-47e5-8157-cc790f68cb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Claims']/parent::*</value>
      <webElementGuid>fd3af635-addc-4599-8fc5-f3e95b5987c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'JavaScript:fireTabRequest()')])[4]</value>
      <webElementGuid>a7f246e6-9599-4aa2-8817-7e0a6abfb2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>3287f976-1be0-4011-9bb9-ac01015b7b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'JavaScript:fireTabRequest()' and (text() = 'Claims' or . = 'Claims')]</value>
      <webElementGuid>f3c541bd-be99-4579-b746-0f24d3c554ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
