<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_List Codes</name>
   <tag></tag>
   <elementGuidId>816d3afd-65ba-40f2-8df7-3a425c230508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(@href, '#')])[145]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e7b370f-f1c1-430f-98b1-e21c6d189b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a781cc84-afa7-49cb-847d-bcf1a1c0673e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>menuAction('/vNEacymXITPwnMNZtOH7YJiGuS53k2S/8tqwdzZhDu/OMaRH/ncFmWNlKtaQylTZ')</value>
      <webElementGuid>55fa5db1-0f22-46a1-93e8-79cfc572d201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>List Codes</value>
      <webElementGuid>c790661e-a009-4556-9ace-8670b6851587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cloud_menu&quot;)/li[@class=&quot;tabsoffline dropdown REFERENCE_active open&quot;]/div[@class=&quot;dropdown-menu pull-left&quot;]/ul[@class=&quot;mainNav&quot;]/li[1]/ul[@class=&quot;unstyled&quot;]/li[2]/a[1]</value>
      <webElementGuid>f0728ea2-3b7d-4b3e-b106-d72e833946e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;menuAction('/vNEacymXITPwnMNZtOH7YJiGuS53k2S/8tqwdzZhDu/OMaRH/ncFmWNlKtaQylTZ')&quot;]</value>
      <webElementGuid>35f9b9f3-833c-4220-a946-8715929c1133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cloud_menu']/li[5]/div/ul/li/ul/li[2]/a</value>
      <webElementGuid>ce3c5d74-edf3-4bb0-8d8b-ad3f5ce0a439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'List Codes')]</value>
      <webElementGuid>ede13a63-cbb9-4050-b787-31a09fe90921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference'])[1]/following::a[1]</value>
      <webElementGuid>3e6308f2-71c7-41bb-9492-6c8a062f27e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='List Codes']/parent::*</value>
      <webElementGuid>a492ff93-6c9b-44bc-9d77-b6f5bc4ca3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[145]</value>
      <webElementGuid>93018852-b7d2-4c99-b39f-45f814562a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li/ul/li[2]/a</value>
      <webElementGuid>6c00ca37-bb89-4d15-8d65-02e2d71f438b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'List Codes' or . = 'List Codes')]</value>
      <webElementGuid>8805c42f-08ad-400e-945f-f26cd2a0f374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
