<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Provider</name>
   <tag></tag>
   <elementGuidId>bc26dbf5-62fc-4178-b893-eef8e9a1cf34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.tabsoffline.dropdown.PROVIDER_active > a.dropdown-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='cloud_menu']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>332f0efa-bf7e-4f8f-a2a3-5e8faba31cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>6d1e57c3-b911-485a-af56-cb197d26cf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Provider,press enter</value>
      <webElementGuid>32999bb6-cca7-4734-a656-e64c518b8f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>ff1f8803-75cf-485d-a6cf-62a444005072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>JavaScript:fireTabRequest()</value>
      <webElementGuid>f708ab8e-301b-46ff-8971-68ff3906eb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>9ce9c6d8-1c33-41de-8f8d-e77fa8f880c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Provider</value>
      <webElementGuid>08f7bb5a-2d79-4f87-9b96-dd9e4bceb936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cloud_menu&quot;)/li[@class=&quot;tabsoffline dropdown PROVIDER_active&quot;]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>0f85bd8c-2a66-4749-8b51-d2bbadb07794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cloud_menu']/li[3]/a</value>
      <webElementGuid>3174127f-e8e3-4112-8604-fe066a1299f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Provider')])[3]</value>
      <webElementGuid>325a940d-1dc6-4a6e-a4d3-8762ee40ab28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Provider']/parent::*</value>
      <webElementGuid>836a2233-cb9f-442e-9ad1-684dbe23bbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'JavaScript:fireTabRequest()')])[3]</value>
      <webElementGuid>2c5de423-32be-4c22-abb6-931a41227205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>273eeb37-92c0-4dc6-bb39-c82838578b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'JavaScript:fireTabRequest()' and (text() = 'Provider' or . = 'Provider')]</value>
      <webElementGuid>fdca929e-02cf-4507-95c1-2dcdc98ce5b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
