<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reference</name>
   <tag></tag>
   <elementGuidId>60779a9f-c4c8-466a-802d-569cb9db9f2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.tabsoffline.dropdown.REFERENCE_active > a.dropdown-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='cloud_menu']/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6addeee0-4e85-4cb4-b980-6cecbeab3a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>fcc6f6eb-1a59-4668-9080-3ccb0a971505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Reference,press enter</value>
      <webElementGuid>c4b75a23-69d4-44c6-abfb-d03283c9ab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>b2915915-e846-4372-91dd-e3fd622b24fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>JavaScript:fireTabRequest()</value>
      <webElementGuid>383cc3bb-7e52-4487-973c-520e98597945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>bc57e869-4b27-4aa0-9c34-64f71f2f99eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>dc6c7de1-4aef-46c6-aebb-63d657e9935b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cloud_menu&quot;)/li[@class=&quot;tabsoffline dropdown REFERENCE_active&quot;]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>a7815603-beec-43ff-a6c3-bccfe602c87e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cloud_menu']/li[5]/a</value>
      <webElementGuid>b22d26d7-4c8f-42cc-bec3-a9b68e3cd24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reference')]</value>
      <webElementGuid>340b7f78-bb5c-4ef9-a307-70765efa842e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reference']/parent::*</value>
      <webElementGuid>5c1a21f8-bf16-4a98-bf42-f8b3b7a42f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'JavaScript:fireTabRequest()')])[5]</value>
      <webElementGuid>ae6d4ee5-65e5-4038-998a-70028fb104fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>d83d99f8-f78f-45d9-ad67-9f19a877b62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'JavaScript:fireTabRequest()' and (text() = 'Reference' or . = 'Reference')]</value>
      <webElementGuid>6eed74e1-dff4-42d4-be91-92f088098299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
