<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>853b2755-0005-447f-b0c8-389d3500ba69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#popup > #dontShowAgain</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dontShowAgain']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03682152-97a8-4211-ab3f-b4be5b919b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-small btnClose</value>
      <webElementGuid>0bb9ccfc-c57e-4f70-b4f9-ca45d76d7632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>532bd63c-2e1b-41d9-9271-63872302c4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close Latest Updates</value>
      <webElementGuid>abe97aea-e815-479c-bff9-0bef5801babb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dontShowAgain</value>
      <webElementGuid>0d75e8b2-a7d0-49a6-b6df-aadaa6dee0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>user_prfrnc_disable_system_notification('/DeKlyI1ZZwNjHyLPJF6GlQlv+SSbYkatp/2XU1pkwakL2idOCsWJ7bwfksK+JfXcpdiYBbsnz3aXehXumXU1P0dudgHb+NtB/lZMyhPWS8L5FREfNmG+1Paslr6TXQcF7J4ypyE8jW2y2a7G5HPo7BQRsmNBAH+/');</value>
      <webElementGuid>656ce00e-1a87-4122-be17-7707aee1e7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                              Close
                        </value>
      <webElementGuid>d72cad75-803e-4b18-b6ee-eefdfa519816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup&quot;)/button[@id=&quot;dontShowAgain&quot;]</value>
      <webElementGuid>742041c7-fd20-4d19-b83e-067f67d93c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dontShowAgain']</value>
      <webElementGuid>8e2656b0-369c-48c7-b727-74f7360c0c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup']/button</value>
      <webElementGuid>77e7676c-eee2-4f3f-8dde-2875053201e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't show this again')])[1]/following::button[1]</value>
      <webElementGuid>9ab95ce5-730e-43f3-adf7-4c1e592338db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/following::button[1]</value>
      <webElementGuid>0c0397f1-d6c6-423c-a790-feb1e11e162b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='skip to main content'])[1]/preceding::button[1]</value>
      <webElementGuid>807921f8-917b-4321-be16-922f64e1d557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Inbox'])[1]/preceding::button[1]</value>
      <webElementGuid>173bf0aa-9108-4535-8bba-d7f14d7a32dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>ea00a9f1-262d-4d17-a515-68baf443bbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>560303b0-4c8a-458e-b854-ecf9d6891988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dontShowAgain' and (text() = '
                              Close
                        ' or . = '
                              Close
                        ')]</value>
      <webElementGuid>ab7f05ea-8c2d-4c7a-9024-8264ed5e1ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
