<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Notepad_admin</name>
   <tag></tag>
   <elementGuidId>5d21eb36-259e-409a-8eca-551efb7f7da0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-menu']/div[2]/div/ul[2]/li[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c98188d1-fd66-41cb-a639-dd38ca3aecce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./images/admin.png</value>
      <webElementGuid>d8ac0a32-b347-4428-989c-e2f2cd383223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>0eb5f059-2bb0-4ab3-8069-97e2c58a8989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Profile Logo </value>
      <webElementGuid>dbfc0da4-6268-4ffa-a4d4-e89c52d4eee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>menu icon</value>
      <webElementGuid>67c853c4-e643-44e8-b449-433a4455c708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;nav-collapse collapse&quot;]/ul[@class=&quot;navbar-nav topbar-nav ml-md-auto align-items-center&quot;]/li[@class=&quot;nav-item dropdown hidden-caret submenu&quot;]/a[@class=&quot;nav-link&quot;]/img[@class=&quot;admin&quot;]</value>
      <webElementGuid>97b35818-0f71-4b22-a65e-52825b09a2dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu']/div[2]/div/ul[2]/li[4]/a/img</value>
      <webElementGuid>d6deca84-f6b8-411e-9cf1-095dab705279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='menu icon'])[20]</value>
      <webElementGuid>1e551f12-3bf0-4666-9f35-1e1823d52459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[4]/a/img</value>
      <webElementGuid>894976a4-d4fb-47cc-932d-dd69efa9c1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './images/admin.png' and @alt = 'menu icon']</value>
      <webElementGuid>0de1f9f9-8574-4506-ac13-08c7f9ce3821</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
