<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Associate CLIA Group</name>
   <tag></tag>
   <elementGuidId>cb52d03d-1ea3-4466-bcb9-2e0bc290bca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgProcedureAssociations</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pgProcedureAssociations']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85950c2e-8c73-4bb6-8c06-1724d6ab230a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>fe28014d-beb7-4b01-8da2-54e90c9f06d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e1b0db4e-02be-4c70-a259-0dd4a45de13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:showMenuOnChange('Generic_PAGE_FRM', 'pgProcedureAssociations')</value>
      <webElementGuid>acb322a9-5abb-4ae2-a6bf-74a6659d71b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgProcedureAssociations</value>
      <webElementGuid>6ea205ce-79fc-4be4-b616-4a3ecc074d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgProcedureAssociations</value>
      <webElementGuid>1243de47-f0c4-40b6-9d81-5a3c00865a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-custom-value</name>
      <type>Main</type>
      <value>/E4Fw7FxAnj2cGIGUtzGsa0cMyIj7voqtmw+sZ8qi4X3KeaN9lnmio1IfiPNdgdbCfsDvGRiENjE=</value>
      <webElementGuid>3e99c94e-baba-45d6-b503-797d0a0f7903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Associate CLIA Group</value>
      <webElementGuid>f1c56bb6-2de3-4d97-937c-12a28a306080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgProcedureAssociations&quot;)</value>
      <webElementGuid>2848e378-8688-45df-bc7b-83a0d1f403ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pgProcedureAssociations']</value>
      <webElementGuid>44fec262-4c2b-4b8f-abe8-0e562b0535d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='showMenuid_0']/a</value>
      <webElementGuid>4f5e4963-bf69-48cf-b0c0-c56e2bfc3772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Associate CLIA Group')]</value>
      <webElementGuid>c2842784-5100-449e-a5b5-7e7f2f879a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[1]/following::a[2]</value>
      <webElementGuid>08914f37-b801-4eeb-908e-7305bc7880b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View History'])[1]/following::a[2]</value>
      <webElementGuid>24c7566e-dc37-4741-a553-aca67a0a9f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShowMenu'])[1]/preceding::a[16]</value>
      <webElementGuid>37795f54-8420-42d2-8911-919ad7c3aaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Associate CLIA Group']/parent::*</value>
      <webElementGuid>e2b4073b-496b-4c16-b62a-ea5e9cbf2aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[574]</value>
      <webElementGuid>76c9ec3b-bd6b-4adb-b067-b1dcbb5a286e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/ul/li/a</value>
      <webElementGuid>ffdf8752-7772-4696-8b02-6f3921e4e68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pgProcedureAssociations' and @id = 'pgProcedureAssociations' and (text() = 'Associate CLIA Group' or . = 'Associate CLIA Group')]</value>
      <webElementGuid>3b659fcf-72cb-49e6-babd-51eac3cd1d8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
