<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Show</name>
   <tag></tag>
   <elementGuidId>71ad6138-ac39-4a07-be04-02fa77962f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShowMenuDropdownAnchor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ShowMenuDropdownAnchor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89d6dbe8-92a8-4a59-9bd1-f957d7e2d381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>de16d485-9eee-4b06-aadc-7b7ab4f042ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>101d3313-0a09-4cd7-982b-423c57d661d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-mini dropdown-toggle</value>
      <webElementGuid>7ca8c43a-711d-4140-9594-a984c89afc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fd0fe81-9054-4286-9886-2e7ec4b83299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show Menu Button, Collapsed. Press Enter to Expand.</value>
      <webElementGuid>48aff5c3-eeaa-42ec-b574-3eacc75027e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShowMenuDropdownAnchor</value>
      <webElementGuid>b4d7ed54-5e54-4d6f-a28e-f3d1c183009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show </value>
      <webElementGuid>dbd2cc6a-2eed-40d1-a718-784c3b8fb66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShowMenuDropdownAnchor&quot;)</value>
      <webElementGuid>387f7868-a3e4-49a2-858e-e642a6b1999b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ShowMenuDropdownAnchor']</value>
      <webElementGuid>5eb99c81-8718-4346-8385-11c9a61a154c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ShowMenu']/div/a</value>
      <webElementGuid>bc8a03f5-5386-4997-8b7b-e7c80f157848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Show')]</value>
      <webElementGuid>4c36f6f6-9297-4041-8052-2afa6882e2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[1]/following::a[1]</value>
      <webElementGuid>20e9d31d-95b2-4277-b4a1-4e40ce7d5794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View History'])[1]/following::a[1]</value>
      <webElementGuid>d1f49e04-bfdf-4b3d-b1e3-76a8e4a908c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShowMenu'])[1]/preceding::a[17]</value>
      <webElementGuid>edcd15c6-7ab8-4322-a4d8-ccd9f088d43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show']/parent::*</value>
      <webElementGuid>bcf1a869-e824-4fdf-9eb8-30e194358435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[573]</value>
      <webElementGuid>38a49b77-a57a-454e-a121-eb1ae55c0351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>1985e6bb-7145-459a-bb39-8b38ee85e3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'ShowMenuDropdownAnchor' and (text() = 'Show ' or . = 'Show ')]</value>
      <webElementGuid>eaf2afc7-a2fb-45f5-82cc-daa56dc1b2a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
