<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>f4e9f27e-bd39-48cd-87ee-c9ba2107d897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CloseButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CloseButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e2e1fe7-93a9-4811-99a2-f7c28528e514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>8a5f2f3a-e68b-40d9-9153-57d801de6e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/9f/zIxRhm0KRw0yhcee5W8skz3eNXA5T5XKgoRIRXA+2/qMNKi4OUksrFAjRy9EoZVZCuYhYtO0tLNm1BMoTuV0eTPWugemj4T5vL+Ki0xPNmI+AMtZ0GlIR4YGe9ULqTQSZTtKYQnjxIDviONc/mjRLPJAFtw4gA9D4WrX2Vj8W0DUWGuZ0hLaWjLZU8wrU3gMoCWw0+OQN+dnouzmC/PlXvfj/zngzbN2lE03or3oqWVgpNhCSh8i/DTbmbhROXxMCnJc/rOlWLszILW4oJl7vMmDoQ25WZ80WkVXM3BEPQbkqfBM64h1jfq0XrMvSPQy81zS7yHqQNROYC8qVWTirIyT/YjcKKg7m+1qpWMzariEsdlxPSUh/FyUpYFnORfJFgdtDkbnpZpgXpB+415MyzK9Y9Ij0aTCKpZkAaUK3Ldei+P0UD0HEfOUbktAiLrzs/AG3VmJzxnLs+ZT/Cfift2EnAt3dVQRBdffQaae1dOPFNR5l8sjvqpyIJH9agwnF/CgtBvTdp1ed2+9yFkSzuwv2YY9ctPBHrbVJlUvnXPcND9Mn3OoB3K38l9vJarlKy8VszZt1tLtINXyrBTtte7nq6qB7</value>
      <webElementGuid>97064f54-2aab-4fdb-9d03-f4beae347c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CloseButton_ACTBUT</value>
      <webElementGuid>31ff8fb0-ff90-4af5-ade5-fe89198c4480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CloseButton</value>
      <webElementGuid>83744449-ab05-4d80-bf56-7901b3b808a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-remove</value>
      <webElementGuid>5fe6d2ab-ac5c-47e9-9f78-2fb77723f650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return datalossConfirmationMessage('closeBtn');</value>
      <webElementGuid>392be042-9f40-471f-ac5e-ec6e0146c1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>c9c7d7bd-8dd7-4939-a222-3113b319152e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>d86bad15-8839-426b-99e9-4690d4f12956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CloseButton&quot;)</value>
      <webElementGuid>dc5abac3-0930-4467-8ebe-114b97ba47c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CloseButton']</value>
      <webElementGuid>b8ce40bd-a1e4-4e93-9017-4f46b7de5132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridBtns']/div/button</value>
      <webElementGuid>376b1b34-a5f3-4805-85f0-c659eb40deb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::button[1]</value>
      <webElementGuid>a998619c-ebcc-407d-9557-b3d2655a546d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[1]</value>
      <webElementGuid>eeacbb01-b8fa-48dd-a822-00ff945867f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View History'])[1]/preceding::button[2]</value>
      <webElementGuid>fd5e7db2-8f6d-42fe-8d5d-4c43a652693b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>2db3dd26-1675-428b-b3cb-9547fe315596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>592eebf6-5f01-4f9e-8e38-7a77eae7225f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'CloseButton_ACTBUT' and @id = 'CloseButton' and @title = 'Close' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>1f1d3fd8-80fc-44f2-9e95-d7ade3141983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
