<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Procedure Code ID</name>
   <tag></tag>
   <elementGuidId>75b99cae-00f6-4d82-b626-4a42bafb5499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='well-cloud']/table/tbody/tr/td/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>06968daf-5210-4d13-a3e8-d68d78d11ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5d14bf1-c5f9-4c3a-80e1-a4bc9a12ea81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Procedure Code ID :</value>
      <webElementGuid>89f18dc8-8566-4deb-ad88-e68e0dd4c9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;well-cloud&quot;)/table[@class=&quot;TableContextTag&quot;]/tbody[1]/tr[1]/td[@class=&quot;span6&quot;]/strong[1]</value>
      <webElementGuid>0fc65468-b5a0-4c42-a982-59189e1bfd0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='well-cloud']/table/tbody/tr/td/strong</value>
      <webElementGuid>7deae8b5-6888-423c-bbf2-77c555dcd083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[evoBrix X]Super Administrator'])[1]/following::strong[1]</value>
      <webElementGuid>3ad145f2-d878-4c49-bf56-1abe15d7e1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[evoBrix X] View Only'])[1]/following::strong[1]</value>
      <webElementGuid>7a20bf6d-cecb-4c9c-b64c-da2041b87f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name :'])[1]/preceding::strong[1]</value>
      <webElementGuid>93404a7c-6d80-4810-85d8-ffc1c193aef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Procedure Code ID :']/parent::*</value>
      <webElementGuid>26f272ae-a57c-45be-b666-c1c47e757eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>34a5a987-2863-40cd-9c87-88f9474dbcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Procedure Code ID :' or . = 'Procedure Code ID :')]</value>
      <webElementGuid>e1245b3b-deb5-49ad-a4d9-35da9138fa32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
