<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>11e5c16c-6498-472d-baa0-b36ff59c4317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CancelButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CancelButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59617cdf-2e5d-4a94-9ddc-4c2eed8ebdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>aa7ab856-6942-4df0-8bdb-ad5550d51506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/12Q+Ui/ypo0WzQV7jlO8GPWbISfSSvYRSBdgmXBPpCg1EQ7pMBpmcN5kz1U1V5jZ8m90luAqPrJxPHIknfs9HxaXbnY6aPDisQmqQRDiQ+PHASorsN0KovUwrdJL2HxVb8KgsjJMsyo2y04ZopqQGMsxWiqCN7YBm03Cgw8hUinJBheVIBGI45zbfNy+CORHwi+f6FZIgtVG4ZSJN9VjXVvKaC9VRh+Kb6wmgIsRfibZE/oZ+Y61P+7hS7dpjvku9GNCMMdRHuSNIRWOf4KV5qFjpPfGhGRBp+aT50uZllauU7FgI5kUQrg0BlcSPqaqV1MjY6Qe6hsiNNfcZ+SjvRYcidrsaK+kN7/LbLSeKCbxJHuNVrwVropg5u558lBmuDb3jCqYggJ5B5sQGZLM4dQzm+I1V9oydGypMVVx6Yn3dmlIbggR82ov+R1U9jrM3wH3hxeoQNdnZ7YiJ+AW9TYoSLcO2CDx</value>
      <webElementGuid>bc0673ec-c1c1-43da-a62b-6c8386ab3111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CancelButton_ACTBUT</value>
      <webElementGuid>a802d4c4-578b-4a4e-806d-698c9a968786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CancelButton</value>
      <webElementGuid>622447b3-fc8f-4899-83a4-e8b88d6471ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-remove-circle</value>
      <webElementGuid>e7bb256f-0163-4804-8957-f73b1db4be02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return datalossConfirmationMessage('closeBtn');</value>
      <webElementGuid>1d5722fa-8a20-477f-aa23-bf0638c508d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>dcce4494-05a7-46ba-bc3b-f86969602b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>18ee8daa-ae13-414d-afc8-08b1b18bb795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CancelButton&quot;)</value>
      <webElementGuid>c84ed5e7-0e4b-411e-828e-0c741cf77527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CancelButton']</value>
      <webElementGuid>93f2e3ed-c726-455b-83eb-fa6449f25deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dlgbtns']/div/button</value>
      <webElementGuid>3ead6ab0-f0b5-4301-8d0e-33a3dc54076b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::button[2]</value>
      <webElementGuid>f9d6be81-671d-4848-b1ce-803dd6cef679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::button[2]</value>
      <webElementGuid>37e48e96-cb12-4316-995b-2df3e85d3d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[1]/preceding::button[1]</value>
      <webElementGuid>82588f58-99a8-488a-9e80-26be36b9c060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page ID: dlgSubmitProfessionalClaimsFinal(Claims)'])[1]/preceding::button[2]</value>
      <webElementGuid>6524ca54-46a5-45be-9da4-ea47b768b7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>e214a4ca-8ba2-46da-85d4-af110fdc25b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button</value>
      <webElementGuid>ec0fd2e5-b81c-441e-935e-f1c03047fdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'CancelButton_ACTBUT' and @id = 'CancelButton' and @title = 'Close' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>55384aa9-c6b9-4ddb-ad23-21dccd0a54cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
