<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1245667229</name>
   <tag></tag>
   <elementGuidId>6d1c2b93-6aed-42c6-b4a7-9734e4b3d7ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingProviderID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='billingProviderID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0007689e-fb54-450e-b9b3-d2d7c56db0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingProviderID</value>
      <webElementGuid>4b0f5f17-a7e9-4680-a07e-3e276cd1917f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billingProviderID</value>
      <webElementGuid>d68cc415-b511-4ea3-8c72-bc5b96264c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6e9ed8a9-f3ca-4840-8004-21aee0622f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Billing Provider ID 1245667229</value>
      <webElementGuid>b81634d7-9f3f-4133-bf9e-57d44cf900f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-left font-n</value>
      <webElementGuid>23ecf02b-dc8c-41b0-a279-c3419dcd158a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
1245667229 </value>
      <webElementGuid>dd723559-d3b1-45e7-8650-bd69007d83a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingProviderID&quot;)</value>
      <webElementGuid>03d718db-ad1f-464a-a675-8a7e1c6c4f97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='billingProviderID']</value>
      <webElementGuid>f87ff327-ea02-45a2-a0d5-83d7b354c845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DlgWrapper']/div/div[2]/div/div[2]/div[2]/label</value>
      <webElementGuid>0e52322b-5224-4b91-bf24-c562d8257aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label</value>
      <webElementGuid>93128943-dcac-454b-b359-36db0d15e02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'billingProviderID' and (text() = '
1245667229 ' or . = '
1245667229 ')]</value>
      <webElementGuid>74faa72f-37c9-4489-a8f0-72c7fdf99739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
