<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_0210815850</name>
   <tag></tag>
   <elementGuidId>44630a24-e1b0-467a-9bc6-b7adc62098b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneficiaryID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='beneficiaryID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3246235e-3871-4f43-9b36-667103032ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneficiaryID</value>
      <webElementGuid>85b87725-92dd-4a99-afa8-8d69c1e2b462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>beneficiaryID</value>
      <webElementGuid>d0378158-2e48-46a5-823a-6c895b7c17d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a4cc47e-77c1-4a1e-9493-3b03bd2d0d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Beneficiary ID 0210815850</value>
      <webElementGuid>f0b81ad4-379d-4157-bc13-6d3c104752aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-left font-n</value>
      <webElementGuid>f7918c60-0c7e-4c40-b55e-0db03e234805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
0210815850 </value>
      <webElementGuid>521c0082-a12d-49d3-a358-40a4130a3c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneficiaryID&quot;)</value>
      <webElementGuid>bc0c857a-0f3a-4823-a0fe-0ccd22c6d8a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='beneficiaryID']</value>
      <webElementGuid>0905f6b9-6141-4f64-a4ba-8c5110f79926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DlgWrapper']/div/div[2]/div/div[3]/div[2]/label</value>
      <webElementGuid>23a02d81-78c9-4b86-acbe-7266a5e90f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/label</value>
      <webElementGuid>e7eea118-ae54-4525-8b02-15245f649f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'beneficiaryID' and (text() = '
0210815850 ' or . = '
0210815850 ')]</value>
      <webElementGuid>7ea3367c-6497-41c2-b995-500310d209af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
