<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_212311710000005000</name>
   <tag></tag>
   <elementGuidId>227442aa-f967-456c-ae86-d8d53733fd1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tcn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='tcn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1787e06f-c53b-4d40-9e02-a2e40683bbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tcn</value>
      <webElementGuid>79b32396-828e-4443-b5a6-60673f2d263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>tcn</value>
      <webElementGuid>f7999ba9-ec59-4e41-8387-941e33ac065e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46b63edd-9ecf-47e9-bd19-11e3743661ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>TCN 212311710000005000</value>
      <webElementGuid>db675508-6538-4630-b91a-fe633efe5fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-n pull-left</value>
      <webElementGuid>5c13f56e-6391-431d-9180-7cec7fa09c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
212311710000005000 </value>
      <webElementGuid>f3a27671-fcf2-4041-88a0-e8053315be86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tcn&quot;)</value>
      <webElementGuid>fb4e59ba-892d-4e86-b875-c4c2d7abf97e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='tcn']</value>
      <webElementGuid>b4dcc6ae-6a60-4d2d-b7d3-03c777fcdec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DlgWrapper']/div/div[2]/div/div/div[2]/label</value>
      <webElementGuid>8c5c7b29-3c3a-4df9-bcba-2dab4eca0efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>d28c3e4b-19c5-4290-90f1-1b5aa7d243ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'tcn' and (text() = '
212311710000005000 ' or . = '
212311710000005000 ')]</value>
      <webElementGuid>381217ef-19d7-4070-8b69-b7e9befaf362</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
