<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Validate Address</name>
   <tag></tag>
   <elementGuidId>5d588734-0df8-400a-9e1a-35f03764b74f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GoButton_providerAddressBean</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='GoButton_providerAddressBean']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c7c248a-43ed-4507-a803-2cf00722c090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>a25d3f3c-bf05-4d85-a347-df3b760a9990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>//buDCiZb8KKzM3BucstSW/KvBjetJfGeMb/UQY5PKmRt3vn0RO5zSkSCHX33S+JBbaGrVlNq5tPX2ZV+pjvE5TQfzrrM15eEdO+14N7RrZk=</value>
      <webElementGuid>4cfec5e0-e88c-44dc-a14b-55e6dc56cc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GoButton_providerAddressBean_ACTBUT</value>
      <webElementGuid>c6a39fc0-cfaa-4642-864a-0720f544b701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GoButton_providerAddressBean</value>
      <webElementGuid>06b0e2b6-94e9-45e9-972f-4ea50b26f4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-validate</value>
      <webElementGuid>2ea2198f-1492-4766-a3f0-1870b8329bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>JAVASCRIPT:callAJAXAddressLookupHandler(this,'_providerAddressBean','providerAddressBean')</value>
      <webElementGuid>60c48afc-d88d-4b31-912a-1e4df9056adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Validate Address</value>
      <webElementGuid>d01b3b27-1523-4b2b-9db7-7dc8275b00aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Validate AddressBilling Provider Location</value>
      <webElementGuid>00681c08-eb4e-451b-b9fe-0f4a70bea265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validate Address</value>
      <webElementGuid>7a2997ca-25f1-482d-8747-126ef48ca5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GoButton_providerAddressBean&quot;)</value>
      <webElementGuid>b013b96c-b0ff-46f4-9d1e-abdd3fdbc5a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='GoButton_providerAddressBean']</value>
      <webElementGuid>6f462f92-50c3-4142-a275-91bbc4ed430e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address_providerAddressBean']/div/div[8]/div[4]/button</value>
      <webElementGuid>c96d4045-a8f6-4749-bcd0-16b8cab924c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::button[1]</value>
      <webElementGuid>8df8aef7-3e4c-4ee0-a70f-a6a08faf8cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Validate Address']/parent::*</value>
      <webElementGuid>d7ba2dfa-f59e-4b75-ac1e-997992c0571a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>42b16bc5-79b6-402e-96ae-128d9f0d7ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Button' and @name = 'GoButton_providerAddressBean_ACTBUT' and @id = 'GoButton_providerAddressBean' and @title = 'Validate Address' and (text() = 'Validate Address' or . = 'Validate Address')]</value>
      <webElementGuid>ab82fbdd-0c03-485e-b506-5fafc429149d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
