<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Service Line Item</name>
   <tag></tag>
   <elementGuidId>9fb89103-7174-4b98-b1b8-a6c1344c90c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addServiceLineItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addServiceLineItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>896b5d31-09ce-48b2-8824-fa948c3340c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>3d5fe2db-23f4-4d47-bc4b-24ff335f3c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/A1JKqFnhsvndUsLnxPyg76D/8apVk9gKWLKuGgZW6rgMpG/IO177QRsKSrNqvMOpcKiPbuZpbOUxbIkEsn9p/9qqBgTuEGbwb7B7/kWVSztr2NAZBQvym+ez57gz5UuQ5r+bPBaJaPpiv27Flt/qq2nmb+R+KKEtFzvOVHesfuXTBnKZz1LVB7SSn0/8DjUK</value>
      <webElementGuid>ec79b9d4-f510-4f16-b97c-b768fa5bf7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addServiceLineItem_ACTBUT</value>
      <webElementGuid>ad65c846-acc5-42d2-8f90-fd8e236faf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addServiceLineItem</value>
      <webElementGuid>3dac1052-e456-416d-89bc-e8a396952bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-plus-sign</value>
      <webElementGuid>6c6c724e-baec-45b5-b303-c629210fe937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return validateProfServiceLineData('Add');</value>
      <webElementGuid>2569b5ab-1ba6-4407-8c5c-36097e47450c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Service Line Item</value>
      <webElementGuid>3a192eb7-51ea-4e90-ac5a-aeed0bf733e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Service Line Item</value>
      <webElementGuid>4de2d4f9-8bb6-4ad1-8a9b-f44d2dfc5042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addServiceLineItem&quot;)</value>
      <webElementGuid>1ebd4901-e7b1-4a10-bc08-2810c2f25ef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addServiceLineItem']</value>
      <webElementGuid>759f26af-9f52-44bc-8d39-b1db8c2ab95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/div/button</value>
      <webElementGuid>77671411-002c-4b41-b2db-dbc96b6a1503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Service Line Item'])[1]/preceding::button[1]</value>
      <webElementGuid>bac08748-0b1c-42cd-903b-4bf4230bb95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Service Line Item']/parent::*</value>
      <webElementGuid>9ee9ded9-262a-417e-a876-a9c3476e7cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>2f1e3f9c-4690-45cd-ba82-da923b3a35a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'addServiceLineItem_ACTBUT' and @id = 'addServiceLineItem' and @title = 'Add Service Line Item' and (text() = 'Add Service Line Item' or . = 'Add Service Line Item')]</value>
      <webElementGuid>2f0546ff-2c3c-4cdb-b577-f9c30f66a0db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
