<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit Claim</name>
   <tag></tag>
   <elementGuidId>1ef6c5b8-08bd-4d71-97dc-2caf4c5bc59d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitClaim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitClaim']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>621f43d2-f3c4-4204-aef6-7225a0c578cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>fd6818cd-abd9-4882-8a68-81a190841ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/5q4GRPoO6PUhrnP9MD12sZ0qaYPcynm4IqLiKMHIf4c5pVysc1KnPfWE7926002jdHoSWKLafpLaFDn6BFl9mbTzpySkPE1bndbQzMsWDLam7NfrGGmzGeulsWnGJ5wuOLPNSXfgzDc=</value>
      <webElementGuid>7987d572-fd2a-46d1-892c-8de05970af43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitClaim_ACTBUT</value>
      <webElementGuid>258c1fd0-889c-477c-ab3f-e3f2af305764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitClaim</value>
      <webElementGuid>eabf6aba-66a5-4c07-baea-a126a78e0171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-ok-circle</value>
      <webElementGuid>10afd5de-d37b-45d9-a8b4-c1cdd7676bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return submitProfClaim('SubmitButton');</value>
      <webElementGuid>c8f6fbd7-80ed-47c8-a45d-67d6ebad6ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Submit Claim</value>
      <webElementGuid>d0ea7f85-2d7a-40aa-a661-003b1e9f9d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Claim</value>
      <webElementGuid>6500d9b2-6e4d-4397-bae1-b4ccbd2aa9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitClaim&quot;)</value>
      <webElementGuid>cb40fbdc-57b2-44b9-9d80-8259a8d746f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitClaim']</value>
      <webElementGuid>0ea0a1fb-bfdb-426d-9dea-29822196ebf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneralBtns']/div/button[2]</value>
      <webElementGuid>66cafce5-747f-4bad-a278-b29acee61aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::button[1]</value>
      <webElementGuid>753471bf-5b1d-4841-aa6a-632bfab5023c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::button[2]</value>
      <webElementGuid>0ea25c8d-5527-4ae1-9134-c5703978f4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save as Template'])[1]/preceding::button[1]</value>
      <webElementGuid>99801278-49f3-4ffa-9d27-e7aed3b71a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::button[2]</value>
      <webElementGuid>641d8252-4d13-4608-a7a7-15f060b83e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit Claim']/parent::*</value>
      <webElementGuid>cb0cd889-5149-43ab-877f-9d33430ead19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>a3a8989b-ac5b-4413-82a8-7c431b332962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'submitClaim_ACTBUT' and @id = 'submitClaim' and @title = 'Submit Claim' and (text() = 'Submit Claim' or . = 'Submit Claim')]</value>
      <webElementGuid>9ae94c91-722f-473e-b9d7-ea5f1060d53f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
