<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Notepad_admin</name>
   <tag></tag>
   <elementGuidId>cf483c86-eec2-44ab-b014-cc0934f1d344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-menu']/div[2]/div/ul[2]/li[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bfb10529-1172-4b66-92f3-e2225a68510c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./images/admin.png</value>
      <webElementGuid>380d7277-3abe-41b0-a217-0298a5f292a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>ac154ef0-5844-4d56-9c27-3d189f583d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Profile Logo </value>
      <webElementGuid>7a49be1a-e350-4e20-b5c7-52a5778f86c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>menu icon</value>
      <webElementGuid>eb1d312b-403a-46d8-bf63-4f51a7f30588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;nav-collapse collapse&quot;]/ul[@class=&quot;navbar-nav topbar-nav ml-md-auto align-items-center&quot;]/li[@class=&quot;nav-item dropdown hidden-caret submenu&quot;]/a[@class=&quot;nav-link&quot;]/img[@class=&quot;admin&quot;]</value>
      <webElementGuid>dfb6f563-e0a1-4222-83e4-b34e7b096a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu']/div[2]/div/ul[2]/li[4]/a/img</value>
      <webElementGuid>845e6dc4-54bc-4874-b861-aeabd0500c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='menu icon'])[20]</value>
      <webElementGuid>dacefd3f-bcb1-463a-8e56-0aaf30b2bb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[4]/a/img</value>
      <webElementGuid>f5c56855-de62-45f8-b101-f84a53f10072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './images/admin.png' and @alt = 'menu icon']</value>
      <webElementGuid>e3caa64f-cd93-4ba4-a20d-12f381d1891e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
