<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_yyyy_serviceToDateYear</name>
   <tag></tag>
   <elementGuidId>d7af5578-da60-4393-adb0-10b8b09c024d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serviceToDateYear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serviceToDateYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f9f3a59-d2c9-4730-a6e9-87698af01ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>68f64204-d9a8-4f03-aa3f-8ef739d2c882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serviceToDateYear</value>
      <webElementGuid>bc5659b1-1591-4748-8dd2-e637cdf298d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serviceToDateYear</value>
      <webElementGuid>a9979afd-22ea-45e0-8565-ee1984473ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('serviceToDateMonth','serviceToDateDay','serviceToDateYear','serviceToDateYear')</value>
      <webElementGuid>c21467e1-fc49-4072-99f2-a3dd0b143e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46f461e6-7743-441b-b407-0518716b0aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>0e9c06c6-3084-4019-8c4d-2a6f654aa709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>To Year</value>
      <webElementGuid>3a94f051-63b3-492b-90aa-38b0c90f1bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6ef7b094-6ad6-41ce-a044-839ebc2838ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>serviceToDateYear</value>
      <webElementGuid>6e4ad3ef-e1de-4fa0-b363-daa0681e429f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>49a61fb6-3a0f-4181-8395-8a7c15ed4c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d64dfa4-e08c-4a70-b183-9d006fda2872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>serviceToDateYear_span</value>
      <webElementGuid>bcaa7437-c663-4633-8982-f832a64e7ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BaseLine Item Information Service To Date yyyy </value>
      <webElementGuid>a0170038-febc-4a39-b027-f748d5b1e162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceToDateYear&quot;)</value>
      <webElementGuid>9f59e7b7-bf15-4fdb-a4f8-08fb46978bb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serviceToDateYear']</value>
      <webElementGuid>cc45ed50-d1e8-4c5a-b684-c6ab23261b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[2]/div[2]/div/div/div[3]/input</value>
      <webElementGuid>0dfb9399-1b60-43a1-8fa4-4d2a4def5490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div[2]/div/div/div[3]/input</value>
      <webElementGuid>179f0e80-407f-4008-be22-6daa9065e567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'serviceToDateYear' and @name = 'serviceToDateYear' and @alt = 'serviceToDateYear']</value>
      <webElementGuid>417aabc3-5bcd-450e-8274-badbc1c8a239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
