<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dd_subClientDoBDD</name>
   <tag></tag>
   <elementGuidId>eaf25ac7-54ec-411f-863c-61c6ed847d9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subClientDoBDD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subClientDoBDD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69428a6a-7df1-4fa7-8e3f-d8097cf45c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>5d7babab-8fd8-41e0-afa3-e5e67a3a9856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subClientDoBDD</value>
      <webElementGuid>ae142574-2617-4217-a95e-408c5507f6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subClientDoBDD</value>
      <webElementGuid>30dcf2e5-895a-406f-8074-bd8aa7c64bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('subClientDoBMM','subClientDoBDD','subClientDoBCCYY','subClientDoBDD')</value>
      <webElementGuid>d913ec7c-7c0e-4d58-baaf-7aa70265d3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoTab(this, subClientDoBCCYY)</value>
      <webElementGuid>d9ccfda6-561a-4056-93d4-cf05fa209152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>68245f81-de6f-453e-b439-970674a30640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>65e925c3-1a3b-4ddf-963f-d16cfbd66b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>e634be24-ebd7-4f66-8bc8-8fa79c3c1004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f1794104-57ea-4a39-88c3-4acb4d041c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>subClientDoBDD</value>
      <webElementGuid>dac96d98-8b64-495e-837e-bd738ce81792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>48f92e32-536d-4f98-94f5-0f68b8a0afd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Date of Birth as Date</value>
      <webElementGuid>92b40f2f-59bc-4d9c-a951-fca150d4fda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Beneficiary Date of Birth dd </value>
      <webElementGuid>03a37eec-be1f-41b7-873c-d59a7524ca0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subClientDoBDD&quot;)</value>
      <webElementGuid>8a1feeee-e6c6-4617-a7a1-2c789591bc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subClientDoBDD']</value>
      <webElementGuid>2d3c39eb-1938-4eae-bc4e-719041d7e15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetbeneficiaryInfo']/div[4]/div/div/div/div[2]/input</value>
      <webElementGuid>5a656163-ebd0-4ac9-9cb6-f847dd2965e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/input</value>
      <webElementGuid>d490bee5-cb09-4faa-883a-1a1591a6fdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'subClientDoBDD' and @name = 'subClientDoBDD' and @alt = 'subClientDoBDD' and @title = 'Date of Birth as Date']</value>
      <webElementGuid>7f4c9492-44fc-42c5-873e-1caa285a9b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
