<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Submitted Charges_submittedCharges</name>
   <tag></tag>
   <elementGuidId>ba91eefe-0005-44ac-960a-727d632d3a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submittedCharges</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submittedCharges']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39afd140-42cc-4507-870d-e1c4b564ab68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>d62128ce-a470-4b85-a6d3-1ae1dfbdf9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>submittedCharges</value>
      <webElementGuid>61601bd0-04dc-46e6-a67b-de6d8ea5d8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submittedCharges</value>
      <webElementGuid>ee24d3ca-930b-4ce6-b129-074177d25519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submittedCharges</value>
      <webElementGuid>ed38c6f6-5bac-4ac8-9b0e-5017f5d36562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>removeCurrencySign('submittedCharges');</value>
      <webElementGuid>70ec9f83-06f5-4f13-bcb1-2cba58008c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setCurrencyFromJavaScript('submittedCharges',10);</value>
      <webElementGuid>4b6b36f2-c8a8-44b2-9601-0292c55020aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return decimalLength(this, 2)</value>
      <webElementGuid>c67bc332-b700-4e3a-812b-9540994fcb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>04f77320-ed38-410b-a294-06c260085d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input input-small errField</value>
      <webElementGuid>369f2314-6c7b-4d43-8c05-6d23bc384964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Submitted Charges</value>
      <webElementGuid>45e58b93-1629-4acb-b436-7d9a55e7ae4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f253e49b-2d00-4492-9d1c-0eeb848922a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>Right</value>
      <webElementGuid>0bb7e223-4279-40ff-a96a-a80f21beedda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>95cba1ed-f696-4dca-946d-1ef32623eaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b4daa56-bbae-46a7-900e-0344e12ba797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Basic Service Line Items Submitted Charges</value>
      <webElementGuid>070c8213-d5d9-4f97-abc6-08d4b3f204f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submittedCharges&quot;)</value>
      <webElementGuid>6c220577-7d46-45d7-a24f-3bdd0742b76a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submittedCharges']</value>
      <webElementGuid>d0ff0fcc-b90c-4a53-ae72-3e6eaeb126e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[5]/div/div/div/input</value>
      <webElementGuid>b21c10a5-4aaf-4a58-a267-50fe75a34f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[5]/div/div/div/input</value>
      <webElementGuid>5f4b12f8-0389-4cd2-a06d-a8cfd01776b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'Text' and @alt = 'submittedCharges' and @name = 'submittedCharges' and @id = 'submittedCharges']</value>
      <webElementGuid>fd5a6103-0230-4147-ac15-935650669632</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
