<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_yyyy_serviceDateFromYear</name>
   <tag></tag>
   <elementGuidId>74475fb4-7740-40f0-b42f-990f53c1c829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serviceDateFromYear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serviceDateFromYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>362b5628-aaa2-4a2b-824f-71292ece61f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>9c9b1880-83bd-44ac-a486-4114425707c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serviceDateFromYear</value>
      <webElementGuid>59b56805-ce2c-4a68-8b70-ae37390c473a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serviceDateFromYear</value>
      <webElementGuid>136b1466-56e2-4481-b90a-51eee96d3469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('serviceDateFromMonth','serviceDateFromDate','serviceDateFromYear','serviceDateFromYear')</value>
      <webElementGuid>31c1387e-9afa-4196-bfdf-6ca2d4f508ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0adcb9ed-ecb2-4b28-aed1-f6601cb47be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>e5c5d781-4723-4ca4-b495-a55b0fa0a604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>From Year</value>
      <webElementGuid>23dc3707-0402-41ea-aab2-4360a8f86856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>60a1ecb7-9789-4d69-89d7-1e53db2490ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>serviceDateFromYear</value>
      <webElementGuid>30422548-781f-4695-9267-b8248ecc2e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>6d4a3716-3488-4bee-91b6-392154040cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34bd999b-1400-4483-8128-2ffff04fbb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>serviceDateFromYear_span</value>
      <webElementGuid>e6a2143c-28f7-4df3-a985-6d6d18e59a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BaseLine Item Information Service Date From yyyy </value>
      <webElementGuid>8a21cf87-0532-4628-9411-4ebfd3880b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceDateFromYear&quot;)</value>
      <webElementGuid>80139ba8-0bcb-4051-a9d6-eb37a841c6c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serviceDateFromYear']</value>
      <webElementGuid>2497fda1-5bff-4e9a-9c78-ee0d1da0ae69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>69a0c0ed-577c-47d5-8dfb-2cd17508467e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>aac36de7-a740-42bb-ba66-ac39d699db07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'serviceDateFromYear' and @name = 'serviceDateFromYear' and @alt = 'serviceDateFromYear']</value>
      <webElementGuid>cec28d97-df98-415c-bf52-120b4131ba48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
