<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beneficiary ID_beneficiaryMemberIdentifier</name>
   <tag></tag>
   <elementGuidId>619ff2db-b899-4a4b-99b4-c0a565adf82b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneficiaryMemberIdentifier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='beneficiaryMemberIdentifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8c6d3ac-253a-4bef-9380-b77686642061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>80c4a467-b6fe-436f-8462-3f3270a2e8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneficiaryMemberIdentifier</value>
      <webElementGuid>6d9ecd2a-b3bf-4747-baee-8dcf67d84bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>beneficiaryMemberIdentifier</value>
      <webElementGuid>6819e81e-6726-48d2-9003-c5d4008c0bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>34b70dc8-2fa7-4ac9-8ea9-9a5e647da3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input</value>
      <webElementGuid>85bd65b2-8a76-4e71-872f-5737381a236e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Beneficiary ID:</value>
      <webElementGuid>032a134f-1d30-4a18-a1e8-b1b3dd706811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8fd83a94-8e9b-4b24-9c5b-21e55ef55bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>beneficiaryMemberIdentifier</value>
      <webElementGuid>2425e85d-5012-4ae4-b9b3-6ee5675e79c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>d3ea3f95-77e9-4803-bbf1-90f378ba4ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>31e70208-700f-4c6c-bc78-ad9889e61c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f1e2655-16c5-46c6-ad34-28c766b185c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>beneficiaryMemberIdentifier_span</value>
      <webElementGuid>891fd79a-d8b2-4833-8695-92eddc9f8b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Beneficiary Beneficiary ID</value>
      <webElementGuid>06225e0d-d85b-4923-9029-34c2e220f940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneficiaryMemberIdentifier&quot;)</value>
      <webElementGuid>7bd42977-6177-448e-b523-53393c6c34a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='beneficiaryMemberIdentifier']</value>
      <webElementGuid>5b46a83e-eca6-48f9-ad8f-1f82e65d092f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetbeneficiaryInfo']/div/div/div/div/input</value>
      <webElementGuid>2d29df44-14a3-4c01-b626-f716b6c44c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/fieldset/div/div/div/div/input</value>
      <webElementGuid>d613e4db-0175-4f78-ab6f-825afdbe94f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'beneficiaryMemberIdentifier' and @name = 'beneficiaryMemberIdentifier' and @alt = 'beneficiaryMemberIdentifier']</value>
      <webElementGuid>e1b30211-9efa-4fce-a827-16a4a0d53d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
