<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mm_serviceToDateMonth</name>
   <tag></tag>
   <elementGuidId>8738e591-2eca-4014-9597-7b6056b17a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serviceToDateMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serviceToDateMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db9df554-a132-42ef-88cd-8f42e72d9898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>efee4353-5240-427f-b04b-ccae1058c7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serviceToDateMonth</value>
      <webElementGuid>36a3260e-da84-4ee3-8119-860fed0802b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serviceToDateMonth</value>
      <webElementGuid>cc6a3ff0-175b-4469-b148-f9e2064e9aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('serviceToDateMonth','serviceToDateDay','serviceToDateYear','serviceToDateMonth')</value>
      <webElementGuid>06e24f80-ae70-4b1f-a3f0-2829ba932102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoTab(this, serviceToDateDay)</value>
      <webElementGuid>d31ae998-36eb-44d7-ac3f-1c6168d3e088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d64fb217-5d43-4742-9910-1908adcf0760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>e929dc53-3699-4794-a238-b3995e04836c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>To Month</value>
      <webElementGuid>a3bc80a2-b4bd-41ce-b24d-5608c3e58db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>173437d4-42c9-43a2-af06-82892696ee19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>serviceToDateMonth</value>
      <webElementGuid>3ae99e0a-bba9-4c30-8be6-6172939cd0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BaseLine Item Information Service To Date mm </value>
      <webElementGuid>08848974-a953-498a-be04-d29c092d5e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceToDateMonth&quot;)</value>
      <webElementGuid>b5428b7a-7679-4acb-9476-efa60850ab51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serviceToDateMonth']</value>
      <webElementGuid>06c78e15-0195-4977-8535-1264c76f8c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>61581263-b97a-466f-aee9-8485dc1b0695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>f2c21c0a-41b5-49a9-b2eb-b5870e4cac49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'serviceToDateMonth' and @name = 'serviceToDateMonth' and @alt = 'serviceToDateMonth']</value>
      <webElementGuid>61902637-7ddf-43dc-8ab8-23bf0f2f5efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
