<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provider ID_billingNationalProviderID</name>
   <tag></tag>
   <elementGuidId>ebce63dc-5a0b-49e0-b2f8-a93217ccf69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingNationalProviderID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingNationalProviderID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbec7523-e6a9-4dd2-901a-5ee19841c425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>0159edc0-e41e-47c6-9461-9edd7b533997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingNationalProviderID</value>
      <webElementGuid>99a4ddfa-2897-42ba-9fd9-89a9204032e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingNationalProviderID</value>
      <webElementGuid>a42aad2a-44c9-479a-ac90-e874a9f9888a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a9465978-28ab-442f-bc66-44106e5f8ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small col-xs-6 col-md-6</value>
      <webElementGuid>1139ab36-1045-4e9f-a598-7703b94dd5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Provider ID</value>
      <webElementGuid>a0f6a4a9-2951-44df-879f-5db4b97e122b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>06458b88-49b4-43b4-906b-bd7a8f9dc069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>billingNationalProviderID</value>
      <webElementGuid>ba8273b7-f7f7-4a56-a985-96b7f2a4552c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>09906ab7-0e96-43b5-83d7-eb87e878e64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>297c62e1-5e20-4b84-b86a-dee1ef1a6032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>74c5654c-3d6d-4eff-8b91-4795683faea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>billingNationalProviderID_span</value>
      <webElementGuid>e89eef4c-b351-4797-a2a6-935b08d47f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Billing Provider Information Provider ID</value>
      <webElementGuid>f2f566b1-83fe-4bb3-a2b8-57a807031089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingNationalProviderID&quot;)</value>
      <webElementGuid>1a6fc016-c652-464e-8909-32b791d6a943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingNationalProviderID']</value>
      <webElementGuid>ba0bd310-b874-4400-821e-fdba3fd7bb56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='billingProviderInfoFS']/div/div/div/div/input</value>
      <webElementGuid>40586666-0643-4aa7-8f90-3a6eefa2b924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div/input</value>
      <webElementGuid>aa5c69fd-0c6d-4271-ad7f-43044d5426bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'billingNationalProviderID' and @name = 'billingNationalProviderID' and @alt = 'billingNationalProviderID']</value>
      <webElementGuid>6a54ce09-a836-4562-8a89-11da13ca0d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
