<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Patient Account No_patientAccountNo</name>
   <tag></tag>
   <elementGuidId>1638245e-21f8-4f4e-b0e5-002021c190c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#patientAccountNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patientAccountNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0641cfea-c9d2-4565-a1ea-6a3d14f93778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>2dbbf270-051b-44a3-9a3a-595006524a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patientAccountNo</value>
      <webElementGuid>c710a0a0-b3de-4c74-a6ef-9fba46a0bd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patientAccountNo</value>
      <webElementGuid>c42dc982-a9d4-4d79-a03a-2a098a90cf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50c4cc5b-f46d-4523-9ecf-03bd553cc0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input Input</value>
      <webElementGuid>c6e179b9-6cc8-4ec4-84dc-8c853e416438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Patient Account No.</value>
      <webElementGuid>5a505b30-8293-4ae1-93ce-6c46d952a298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>35c586cc-fdf5-47d9-87ba-3e05444f44e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>patientAccountNo</value>
      <webElementGuid>cac824e5-205c-4e4d-a87a-eb90ef369cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>c5e61b47-c29a-40e9-83e0-55a105d2e2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04975697-e730-4b7e-8ffa-eebec74c74cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81c5bdca-f986-4a3e-93c7-b1bb3f5589eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>patientAccountNo_span</value>
      <webElementGuid>f67ff1bb-708c-4cbd-b4c5-2212c2b7c023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ClaimData patientAccountNo</value>
      <webElementGuid>9f39915b-18ff-42f1-a00c-5324cd05ebd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientAccountNo&quot;)</value>
      <webElementGuid>6199bde2-c9db-4c90-9a38-7b713facb1b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patientAccountNo']</value>
      <webElementGuid>563d4ae6-dd5a-40e0-a1db-2b8d8290dca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[6]/div[2]/fieldset[4]/div/div/div/div/input</value>
      <webElementGuid>7cc85034-d413-45cc-823c-462778298789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/div/div/input</value>
      <webElementGuid>f71aae15-b3a4-4f9b-8131-5dbce15bbcce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'patientAccountNo' and @name = 'patientAccountNo' and @alt = 'patientAccountNo']</value>
      <webElementGuid>ac7f4585-2e50-4c52-9dcf-d505bfff4e41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
