<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_patientLastName</name>
   <tag></tag>
   <elementGuidId>4bb6bfec-b3a5-4d8a-9210-b293dc973bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#patientLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patientLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9e3f651-8fd2-4ef0-9e08-4cc0cb74f925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>d5b87073-19ea-4da4-8f60-7e78ea4c3c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patientLastName</value>
      <webElementGuid>c2b65af0-64dc-4221-9c0e-90c50870e3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patientLastName</value>
      <webElementGuid>0811e8a0-af57-42b2-a857-b576b9e15854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1291f032-64f8-4dbf-a659-ae0c6ffe33d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input col-lg-6 col-md-6 col-sm-6 col-xs-6</value>
      <webElementGuid>446b4aa5-0d1b-44a9-b3e0-6e82f47df13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Last Name:</value>
      <webElementGuid>f02b1cd9-6c5d-4ec6-8f62-7535edc994d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>8aef3b1b-cb9c-4528-9c44-1eafeb7ecfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>patientLastName</value>
      <webElementGuid>7fdf3554-d277-4a18-819f-e6c4be6cc33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>ac1260de-b101-4269-b97d-e40b2d21c2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88a97153-372e-4eec-a90d-c62595fe0bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58b8bd27-6a9e-4eb2-a267-ea127a06ce31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>patientLastName_span</value>
      <webElementGuid>4d0fdc3b-e773-4296-8317-4b22e2ab20d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Beneficiary Last Name</value>
      <webElementGuid>8ebba429-db99-4c3a-8c1f-e84e9dd51314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientLastName&quot;)</value>
      <webElementGuid>a50d883e-b546-408a-bb49-bb037efd2bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patientLastName']</value>
      <webElementGuid>c007e770-b0c7-439a-8556-4b1a9ce2e9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetbeneficiaryInfo']/div[2]/div/div/div/input</value>
      <webElementGuid>a339a313-b4ce-4ea5-b1aa-62f91ab7efee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div/div/input</value>
      <webElementGuid>cbad3221-69e9-480a-972e-150a7e999600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'patientLastName' and @name = 'patientLastName' and @alt = 'patientLastName']</value>
      <webElementGuid>bb45b35b-2b14-4597-9d03-19acb28eba54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
