<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mm_serviceDateFromMonth</name>
   <tag></tag>
   <elementGuidId>51938a2f-32c3-4f85-93d7-f0ab24e6b40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serviceDateFromMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serviceDateFromMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50874693-1159-484a-98c6-bf46fc97d76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>3aea6824-7662-4c2b-94c7-0211d023e145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serviceDateFromMonth</value>
      <webElementGuid>ccfd55f4-8972-4291-ac89-71c544fc345f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serviceDateFromMonth</value>
      <webElementGuid>4cb920e6-e6db-4541-aff3-c03f91f3ff44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('serviceDateFromMonth','serviceDateFromDate','serviceDateFromYear','serviceDateFromMonth')</value>
      <webElementGuid>a2442850-2de3-443f-aabf-ea86cc553f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoTab(this, serviceDateFromDate)</value>
      <webElementGuid>fa58ac65-535f-4819-aeb6-c331e59ed314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1451ee21-ebf2-4203-9a9f-fc883afef8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>2ccfed0a-9225-44f1-bca0-09ba21e4008e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>From Month</value>
      <webElementGuid>bec66359-04e7-47fb-ad96-4b8adecb1101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5bd0ebec-4c19-4936-bcef-3ed0e0ef553c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>serviceDateFromMonth</value>
      <webElementGuid>04877519-9176-4349-b098-97be22fa8eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BaseLine Item Information Service Date From mm </value>
      <webElementGuid>5a084336-e35c-4eb6-9e6f-05ae84685384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceDateFromMonth&quot;)</value>
      <webElementGuid>e408a3f5-d005-42db-ba59-9ddf3655e758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serviceDateFromMonth']</value>
      <webElementGuid>0ee6aa35-a01e-4e3b-8ac9-db2083960389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[2]/div/div/div/div/input</value>
      <webElementGuid>f301f8b5-ce3a-43da-a325-638d10bbc81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div/div/div/input</value>
      <webElementGuid>bf792013-5b0f-48b9-b9cd-2ef19320727b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'serviceDateFromMonth' and @name = 'serviceDateFromMonth' and @alt = 'serviceDateFromMonth']</value>
      <webElementGuid>ca223053-23b0-4292-bd0c-b4b3e4ddb240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
