<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_yyyy_subClientDoBCCYY</name>
   <tag></tag>
   <elementGuidId>ca2b78ce-54d6-4cb0-89f3-e00ad267064e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subClientDoBCCYY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subClientDoBCCYY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>246223a7-c637-4e21-a523-e7ae5b9bdcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>f311a8e3-2335-4cd9-ab47-84d6e8753d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subClientDoBCCYY</value>
      <webElementGuid>b63372d2-63bf-4dc1-8b79-af65b5a06346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subClientDoBCCYY</value>
      <webElementGuid>67bd8981-554c-4f61-8c2d-e0c61571778b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('subClientDoBMM','subClientDoBDD','subClientDoBCCYY','subClientDoBCCYY')</value>
      <webElementGuid>22bf6e36-a883-4e48-a047-e7f04baeac41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f9cbddc6-4768-4ac9-95e3-53b2def86a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>ceb0d137-b5af-409a-a839-325d2e8d2a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>bee7c264-9065-4a8b-a874-9319b0f29de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>37ae17fe-bf46-4eb0-a0a0-eaac169db77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>subClientDoBCCYY</value>
      <webElementGuid>33cdc6bf-7bcc-4e88-b952-0e67bd2fe5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>70b8bd1b-f118-419d-aefc-2aa36b72cd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41675a4d-3d43-4348-b750-4bfb2dbb11b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>df9154ed-fe5f-41df-b631-ead873c96ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Date of Birth as Year</value>
      <webElementGuid>cbae783f-0dac-4f3a-8cfb-bfd6498bdde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>subClientDoBCCYY_span</value>
      <webElementGuid>3abec3d8-62cb-4a1b-8fcb-0fc709ea3f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Beneficiary Date of Birth yyyy </value>
      <webElementGuid>d9b46488-2366-40f2-9b40-933a1f992b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subClientDoBCCYY&quot;)</value>
      <webElementGuid>d5925994-580b-4864-81ca-f175cc0eca37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subClientDoBCCYY']</value>
      <webElementGuid>2a1429ad-7d8c-444c-9188-553a7bfbb25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetbeneficiaryInfo']/div[4]/div/div/div/div[3]/input</value>
      <webElementGuid>c1652f14-6b3e-4645-8cba-53ddc268a5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>cbe8a71a-379b-4fb0-bead-2556efe171ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'subClientDoBCCYY' and @name = 'subClientDoBCCYY' and @alt = 'subClientDoBCCYY' and @title = 'Date of Birth as Year']</value>
      <webElementGuid>ac760228-6ce5-42b2-b793-ff5e97e6440f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
