<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Line 1_Address1_providerAddressBean</name>
   <tag></tag>
   <elementGuidId>6accf218-2056-47b9-9fd3-3cfad9f0a832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address1_providerAddressBean</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address1_providerAddressBean']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a5d9fbc-4d44-407d-a159-25d7b487d894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>7385bb8b-b940-474b-86c3-dd29a289c13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address1_providerAddressBean</value>
      <webElementGuid>7d114575-cd70-4133-a959-c17a045ab338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address1_providerAddressBean</value>
      <webElementGuid>68406f3c-4205-48e8-b1aa-f17352c2df01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setAddressDirtyFlag('Y','_providerAddressBean','providerAddressBean');null;</value>
      <webElementGuid>3e078f3e-046b-46c4-a4ae-8a843f772be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02ad093f-8925-4d85-90b9-f8bb2e5b9bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextBoxMedium</value>
      <webElementGuid>87c4d964-dd17-4209-891e-fae6930c4998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Address Line 1</value>
      <webElementGuid>798988ba-4385-492c-abd4-adae999f3ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>79aaafaf-0f56-4e51-9b76-494df254e7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Address1_providerAddressBean</value>
      <webElementGuid>47800d9d-a818-46e3-857a-ff66e3587b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Billing Provider Location Address Line 1 Required</value>
      <webElementGuid>c3066f5a-acf4-4ea5-8025-5ce6df06f38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address1_providerAddressBean&quot;)</value>
      <webElementGuid>db445760-da40-4df8-b239-daf7a55c5d27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address1_providerAddressBean']</value>
      <webElementGuid>979e2999-cbab-47d4-96dc-1172ed764bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address_providerAddressBean']/div/div[3]/div[2]/input</value>
      <webElementGuid>26d36733-942e-4e23-8d71-bfbd91730736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div[2]/input</value>
      <webElementGuid>1e599363-31f2-477b-8991-c5dfdc04c2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'Address1_providerAddressBean' and @name = 'Address1_providerAddressBean' and @alt = 'Address1_providerAddressBean']</value>
      <webElementGuid>0b394cb1-fba1-4565-b845-75ea1454ce7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
