<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mm_subClientDoBMM</name>
   <tag></tag>
   <elementGuidId>1bc7d5d8-eed9-4e1a-ad0c-f193702c9568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subClientDoBMM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subClientDoBMM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c231e158-a050-45af-9d13-bcbb460c6a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>335f8615-1b5d-48f8-ae23-73e3f8644037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subClientDoBMM</value>
      <webElementGuid>700f592d-edaf-4811-9398-421f65acaee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subClientDoBMM</value>
      <webElementGuid>a7d0263e-b081-49bc-9db3-acc830fb5ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('subClientDoBMM','subClientDoBDD','subClientDoBCCYY','subClientDoBMM')</value>
      <webElementGuid>2e0cb831-969d-47ff-93e7-1254f2818321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoTab(this, subClientDoBDD)</value>
      <webElementGuid>5bbdc1c0-e47e-40ff-82e1-096d0ca082fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1165e9f7-b3b4-46a3-ab51-c7a2414c3ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>872137a5-c177-494c-8027-476e5f2f03b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>08f8af49-c369-41fb-9c1e-9f43db0e5414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>74e59b89-0554-4e8e-8e13-c7fc1a0837ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>subClientDoBMM</value>
      <webElementGuid>eada9370-985f-4e55-847b-e27eea95e6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>b18ee01d-ddd9-431a-a783-4cb790eaea77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Date of Birth as Month</value>
      <webElementGuid>521fb98c-14d6-425d-a339-338d5a320566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Beneficiary Date of Birth mm </value>
      <webElementGuid>f11bf5a0-f201-4a55-a80a-749bf26120c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subClientDoBMM&quot;)</value>
      <webElementGuid>f5b216d6-c417-4fbf-9f80-bf4c14169fed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subClientDoBMM']</value>
      <webElementGuid>2881d75c-ccaf-4aff-821a-91180b0ae17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetbeneficiaryInfo']/div[4]/div/div/div/div/input</value>
      <webElementGuid>f21053ef-de22-4b9f-ae17-36f94b1093a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[4]/div/div/div/div/input</value>
      <webElementGuid>d0f537ca-a26b-45e1-ba2b-74ae72e18534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'subClientDoBMM' and @name = 'subClientDoBMM' and @alt = 'subClientDoBMM' and @title = 'Date of Birth as Month']</value>
      <webElementGuid>10b69bb7-e36c-4607-a3a5-e20258a35cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
