<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dd_serviceToDateDay</name>
   <tag></tag>
   <elementGuidId>9f822ed2-1059-499b-a30f-49793eb91bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serviceToDateDay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serviceToDateDay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef2b9795-258c-4468-88d5-e81d8ff20fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>ba968531-1a38-40c7-b7c1-2343356ccb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serviceToDateDay</value>
      <webElementGuid>3b7bade3-3f7f-4dc3-a31c-3d921df7390f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serviceToDateDay</value>
      <webElementGuid>0fc314c8-ca4d-4978-be1d-36c1d8a7b0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('serviceToDateMonth','serviceToDateDay','serviceToDateYear','serviceToDateDay')</value>
      <webElementGuid>d729ac81-f9be-462b-b16a-33da06546867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoTab(this, serviceToDateYear)</value>
      <webElementGuid>21fa6c71-f63e-4b17-913c-9ebd046a6331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd71cabb-8ad6-41af-83a2-8bf9f971868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>f196cf42-5066-4f1d-8137-18694ea15732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>To Day</value>
      <webElementGuid>1a23fdf5-e679-4e85-bd2b-5b64c3964328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5695688b-cb39-439c-910a-0fc183932cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>serviceToDateDay</value>
      <webElementGuid>cece688c-60db-4a1c-b380-e76d76f11846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BaseLine Item Information Service To Date dd </value>
      <webElementGuid>b1cead91-cd99-46e0-b204-f07e232e88bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceToDateDay&quot;)</value>
      <webElementGuid>672fe8e9-6065-4b15-9e51-594849354d76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serviceToDateDay']</value>
      <webElementGuid>4efdb884-2650-43b0-91f6-0bfd3da0d172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>4749171e-bf63-4d3a-aa9c-134cc925e1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>74a2b617-728d-4dca-8d6d-11efaaab2ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'serviceToDateDay' and @name = 'serviceToDateDay' and @alt = 'serviceToDateDay']</value>
      <webElementGuid>9bbf99ba-1b98-4cda-923f-d0c31c5105f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
