<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UnitsQuantity_unitsQuantity</name>
   <tag></tag>
   <elementGuidId>ee53d5ec-ae7c-4560-a3a0-66cb1aaecf7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unitsQuantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitsQuantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5e2a9ee-76d6-41c6-bf10-72590410159d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>3e48348c-edd3-4285-8254-49b64ba45833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitsQuantity</value>
      <webElementGuid>f7cbccd0-7a62-4961-8c89-939119bac372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitsQuantity</value>
      <webElementGuid>874c8db5-edc6-4f48-adb1-195c64527613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d421e204-4f2e-4a54-9c75-7999bf6ed2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input input-small errField</value>
      <webElementGuid>b0e88566-0acb-4444-add3-583995cdba2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Units/Quantity</value>
      <webElementGuid>ff7d9fe3-55d2-4da2-9594-353af0c3bc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>46256433-3574-4e08-94ac-fa3eeee6d402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>unitsQuantity</value>
      <webElementGuid>78c0408f-f0bd-4343-94ed-580458ce2b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>a8b9eb50-124e-43cd-a075-b4f8b919283f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1631246b-11af-4ada-a4c9-faf825a6ea6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2022b408-2582-4b1d-9e0d-78b384af833a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>unitsQuantity_span</value>
      <webElementGuid>48ebfe36-97f3-4d83-a1b3-f31539943214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>unitsQuantity Required</value>
      <webElementGuid>91133986-1538-4351-a31c-d7e26411a731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitsQuantity&quot;)</value>
      <webElementGuid>f542d190-d54e-4dee-a355-4b81088b6518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitsQuantity']</value>
      <webElementGuid>a041fc53-47b1-409d-9a1d-82c1fb31eee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[7]/div/div/div/input</value>
      <webElementGuid>fcb0514b-9d77-4c03-9574-a1761a7c7288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[7]/div/div/div/input</value>
      <webElementGuid>ea18357b-1ee0-46c6-931e-3b0de6e6125e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'unitsQuantity' and @name = 'unitsQuantity' and @alt = 'unitsQuantity']</value>
      <webElementGuid>243313d0-e4b8-4254-875c-f5188c14824e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
