<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_POSTAL_CODE_providerAddressBean</name>
   <tag></tag>
   <elementGuidId>4e32b9af-53a8-4927-8f9b-dfe90fef24e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#POSTAL_CODE_providerAddressBean</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='POSTAL_CODE_providerAddressBean']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc1c850f-13f0-4e0c-bd4d-6059e0f375b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>9330f115-ee85-49ad-975d-bb9f94d2d19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>POSTAL_CODE_providerAddressBean</value>
      <webElementGuid>08bf1f14-a750-4407-b3b3-aab8e953cbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>POSTAL_CODE_providerAddressBean</value>
      <webElementGuid>bdc72e33-68ad-4e16-89de-a6f81ab0345d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setAddressDirtyFlag('Y','_providerAddressBean','providerAddressBean');null;</value>
      <webElementGuid>624a20a1-8f58-4235-9529-70d6d0305a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberKeyCheck(this,'_providerAddressBean');</value>
      <webElementGuid>db492c55-f90d-4b1e-9eda-cadbc11cc433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return isNumberKeyCheck(this,'_providerAddressBean');</value>
      <webElementGuid>66808b73-926f-4d85-ad4b-b0ce875fe29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99a9cca6-7a8a-4889-9e7b-bb027ec71996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextBoxMedium input-mini</value>
      <webElementGuid>e3cbc033-e896-4bb8-865d-134716b37b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Zip Code</value>
      <webElementGuid>7dc7d4a1-9e1d-486f-9151-be1ae321ba33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f17c0842-2cbb-4465-bda3-2909e34c42a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>POSTAL_CODE_providerAddressBean</value>
      <webElementGuid>4d0e963f-ac3b-4467-a4fb-06f98463ab6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Billing Provider Location Zip Code Required</value>
      <webElementGuid>89cfce8e-7f99-4a74-bfbe-8e067eb7a2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;POSTAL_CODE_providerAddressBean&quot;)</value>
      <webElementGuid>3b316f50-c51e-4385-aae0-15d1d4a89786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='POSTAL_CODE_providerAddressBean']</value>
      <webElementGuid>a3aa02cd-4549-442d-9a68-895395b99982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address_providerAddressBean']/div/div[8]/div[4]/input</value>
      <webElementGuid>466c5f95-326a-4449-af16-7c9d4a03206e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[4]/input</value>
      <webElementGuid>53cc02d2-15f6-489f-b3d8-b453dd4b8eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'POSTAL_CODE_providerAddressBean' and @name = 'POSTAL_CODE_providerAddressBean' and @alt = 'POSTAL_CODE_providerAddressBean']</value>
      <webElementGuid>8f93266e-58a4-49fa-babc-8c2878522ad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
