<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Diagnosis Codes 1_diagnosisCode1</name>
   <tag></tag>
   <elementGuidId>9a78006f-c0d3-495e-8439-f52ac187f911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#diagnosisCode1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='diagnosisCode1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48189679-d8c9-4db8-9dd4-74f518b5bde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>f85ea0d9-0917-4508-860a-b25c74d298a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>diagnosisCode1</value>
      <webElementGuid>cd3c5c08-1c1e-4be4-b852-e8986aa963c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>diagnosisCode1</value>
      <webElementGuid>75998650-7de1-4ed9-853c-77ffc49e786d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63040147-f211-44e8-9c92-dec1e8072cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input input-mini</value>
      <webElementGuid>0b93abd8-c00f-4e37-964e-12c94f960754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Diagnosis Code: 1:</value>
      <webElementGuid>30eef8b0-b3b2-411f-881a-78fcd0873e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>243f4d2c-eb46-42f8-a4d7-1da1cbaec53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>diagnosisCode1</value>
      <webElementGuid>387e059a-02ed-4af5-a0f4-b5c78cc5fa29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>03802a9b-d2ae-4161-bb0e-5ab7f9cae286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4f39434-11dc-4951-8095-b1dc7186b6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08477ad1-efc5-4d8d-a3fc-783a00758336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>diagnosisCode1_span</value>
      <webElementGuid>005c05f7-bd9e-4136-8f80-f7bc7a6a9fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>diagnosisCode1 Required</value>
      <webElementGuid>94e5260c-3d9e-4e3c-baf4-88f4d6242260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diagnosisCode1&quot;)</value>
      <webElementGuid>bd28b919-b91a-4c4e-9d00-217d37d11614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='diagnosisCode1']</value>
      <webElementGuid>b25ba39e-5e38-4148-aaa6-91f0d74bc48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='diagnosisCodeDiv1']/div/div/div/input</value>
      <webElementGuid>05efc8ef-f24a-43a7-858b-8ebf49dff92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/input</value>
      <webElementGuid>5067b7e1-fefc-4e2a-8b54-d2cd88b42f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'diagnosisCode1' and @name = 'diagnosisCode1' and @alt = 'diagnosisCode1']</value>
      <webElementGuid>58f0b066-43eb-4808-9fd3-1ee6b1c92a0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
