<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Modifiers_modifiers1</name>
   <tag></tag>
   <elementGuidId>e7c81006-279f-4ebd-aa64-d3aa59e2e77c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modifiers1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modifiers1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b417652e-af36-45ee-8e13-207495b09b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>2071b8c5-f145-4071-9eae-39e4ef510ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modifiers1</value>
      <webElementGuid>4a186400-efdc-4fc8-82f8-3442a3ef9290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modifiers1</value>
      <webElementGuid>a85276b1-2d6f-429f-8bf5-998273462da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e5b9f0d-125b-411a-a5a6-0963b1c91abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>claims_span6</value>
      <webElementGuid>d4a781ae-40e3-4e2b-92bf-a512100b4d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Modifier 1</value>
      <webElementGuid>5cddb27c-7aa2-4471-a001-fd7a9b19b1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c5ac02b6-7133-490b-9a8a-dfa6d59b97e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>modifiers1</value>
      <webElementGuid>464e00c4-85e4-4b10-81a7-af0382391f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Modifiers 1</value>
      <webElementGuid>3d1d175c-9235-4320-9d1c-cf1af567a36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modifiers1&quot;)</value>
      <webElementGuid>1d1bbc30-2460-46c8-8abf-b57d420d126d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='modifiers1']</value>
      <webElementGuid>5548b6fa-4611-457e-813b-eabe8c1c42af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>510dce32-beb6-4201-9d4f-a9370c6253c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>bf9c5a97-d729-4536-8c23-25c28327cb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'modifiers1' and @name = 'modifiers1' and @alt = 'modifiers1']</value>
      <webElementGuid>dd99a414-b7c6-4a41-84f9-9903e8bd3a16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
