<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dd_serviceDateFromDate</name>
   <tag></tag>
   <elementGuidId>15ad7bfc-9bc6-4240-ac8d-bbfdf50577bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serviceDateFromDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serviceDateFromDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a89bc263-a566-41d2-8efd-f5e91c8690bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>a3789396-0ef2-4dab-a13a-8cc5342a6e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serviceDateFromDate</value>
      <webElementGuid>7ab1fdc3-77c8-48f1-8940-6dfee146f16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serviceDateFromDate</value>
      <webElementGuid>6d901e3c-bea9-45ee-941d-68cde6d12c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearCVM('serviceDateFromMonth','serviceDateFromDate','serviceDateFromYear','serviceDateFromDate')</value>
      <webElementGuid>e0a7b4e5-3f23-41ee-ad08-96ec97875e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoTab(this, serviceDateFromYear)</value>
      <webElementGuid>6a4d8547-79c5-49cb-aa7e-d29a078426c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>912bdba4-cfb5-4d58-8776-40a50584347b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input span1 date-center</value>
      <webElementGuid>5e91ce03-7e6b-454b-ab69-8287596961a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>From Day</value>
      <webElementGuid>4611fbaf-d7a9-4f53-936b-88eb444ce313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7cd6d92c-d167-4078-9bfb-56166870a348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>serviceDateFromDate</value>
      <webElementGuid>a24e63cb-08dd-4505-bfa4-0ea4ec6f9a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BaseLine Item Information Service Date From dd </value>
      <webElementGuid>3758f9de-1f1a-4d75-b39b-0e7f1a3139ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceDateFromDate&quot;)</value>
      <webElementGuid>33de9f8d-33be-4c62-a0f3-659b06fa762e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serviceDateFromDate']</value>
      <webElementGuid>ce2475e2-9cd6-4b83-9c13-df12fd05491d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>2dc13a37-5600-4446-a184-60351787d8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>cc8800ed-5755-443c-8293-8b676bb69022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'serviceDateFromDate' and @name = 'serviceDateFromDate' and @alt = 'serviceDateFromDate']</value>
      <webElementGuid>2819a686-019e-4d7f-92e3-0c4bb27f6a0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
