<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Procedure Code_procedureCode</name>
   <tag></tag>
   <elementGuidId>5e535422-894d-4d41-9117-098ebb9454a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#procedureCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='procedureCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0580b41-3a66-4f46-8358-3171c513c537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>45db8634-29c4-4100-abdb-97e2a6c6ab36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>procedureCode</value>
      <webElementGuid>6deb0f76-275f-4501-a757-0f213ff9783b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>procedureCode</value>
      <webElementGuid>fe1964a1-a7db-4b38-8f55-05455aef9e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ed7d986-4c0a-4d63-9832-930d419cad75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input input-small</value>
      <webElementGuid>f66e35c6-2c99-44fc-af42-368d2f4eed4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Procedure Code</value>
      <webElementGuid>e00fe377-fc35-46ec-855b-37f6932d4ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b0670d9c-60ca-49a5-85c4-2d9caf71df92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>procedureCode</value>
      <webElementGuid>2fd68eb0-ac73-44f1-a05f-20d695d01031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>71a305d2-e974-4a71-9912-54b8c9d4a361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c1e84ac-cd77-4e0b-86f3-5b0b870b3e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dbe4a27b-a043-448d-b035-51d76224572a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>procedureCode_span</value>
      <webElementGuid>bc4d2af8-cc13-4754-81b1-1afa11502838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Basic Service Line Items Procedure Code</value>
      <webElementGuid>fa55d4c5-1d28-4f9a-bd5d-d6f182a45d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;procedureCode&quot;)</value>
      <webElementGuid>14097477-1918-488b-b620-0b75334d8de7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='procedureCode']</value>
      <webElementGuid>1d05bbf4-6f26-4490-b0d8-610249d972da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgGeneral-wrapper']/div/div[2]/div[7]/div[2]/fieldset/div[4]/div/div/div/input</value>
      <webElementGuid>2c2805e9-0531-4575-a774-fac3a2cfa17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[4]/div/div/div/input</value>
      <webElementGuid>365b2252-7227-4a30-b076-6be3d4cd0f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'procedureCode' and @name = 'procedureCode' and @alt = 'procedureCode']</value>
      <webElementGuid>3c4fd6d7-a947-453f-8f2e-ee93e0f7e6f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
