<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Yes</name>
   <tag></tag>
   <elementGuidId>c26b5dfb-2583-444b-a650-15038a216d7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='questionmark']/div/label)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>07cb1fb4-2c01-4011-b5a5-43d63f431032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billingRenderingProvider0</value>
      <webElementGuid>b0ccf2a4-a383-44b5-b519-51b8ee535323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>d180f55f-60e5-49f6-9dfe-451123266c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgGeneral-wrapper&quot;)/div[@class=&quot;widget-box&quot;]/div[@class=&quot;widget-content&quot;]/div[@class=&quot;widget-box margin-top5px&quot;]/div[@class=&quot;widget-content&quot;]/div[@id=&quot;claimboxmockup&quot;]/div[@id=&quot;questionmark&quot;]/div[@class=&quot;pad-top5px col-lg-offset-5 col-md-offset-7 col-sm-offset-7&quot;]/label[1]</value>
      <webElementGuid>edbc9cc4-6401-4076-b86f-0b24d7c085b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='questionmark']/div/label)[3]</value>
      <webElementGuid>c271f07e-d6d3-4b3d-b6f9-5b024c4db0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate Address'])[2]/following::label[2]</value>
      <webElementGuid>9fee3748-7fb1-46f1-a639-245524054ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::label[1]</value>
      <webElementGuid>185bbd56-1ed7-421e-b02d-b800d1097755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>3f664f6d-a89a-451c-9e2f-aacf56013908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>9faa5fbb-3d07-4a49-b796-12a7d6031de6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
