<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NPIProvider ID</name>
   <tag></tag>
   <elementGuidId>e65de3f7-5881-41fe-a105-ab730b9e8c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingProviderIdentifierTypeCID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='billingProviderIdentifierTypeCID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>581d15e1-2b38-4b97-bbe1-22e0a64217dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>884aeb73-8f6c-4335-9306-d72e22774dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingProviderIdentifierTypeCID</value>
      <webElementGuid>809e2adb-06a9-4103-bb5a-e3dd161ce65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small col-xs-6 col-md-6 </value>
      <webElementGuid>14e3180a-dfbb-427a-bb24-341a62ffa2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>f3fc7e56-0e6a-42cc-9311-44136d1cee88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingProviderIdentifierTypeCID</value>
      <webElementGuid>436e6590-12a4-455d-be8b-1ada696571e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-req</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>fd24dd1d-e4db-48b3-b85b-fb237dbcc1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42d67822-56f9-4bc4-b4b0-88fe8e98c0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>cmb</value>
      <webElementGuid>f444061c-3db6-4905-aabe-f075eea64e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate-group</name>
      <type>Main</type>
      <value>billingProviderIdentifierTypeCID</value>
      <webElementGuid>566cb761-fc0a-4270-9393-0cb904706631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>billingProviderIdentifierTypeCID_span</value>
      <webElementGuid>eb5f5fac-b02d-474c-a892-20092e528696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Billing Provider Information Type</value>
      <webElementGuid>185c48b0-da03-4d10-a64a-85b0df724677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
     
NPI
Provider ID
</value>
      <webElementGuid>ebc7c5c7-a66a-4ccf-8918-7873690fc163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingProviderIdentifierTypeCID&quot;)</value>
      <webElementGuid>8f5ff97d-3301-40af-9a7e-87e272c6aaa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='billingProviderIdentifierTypeCID']</value>
      <webElementGuid>2f0d868d-2f46-4767-84a5-7d1d125ccb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='billingProviderInfoFS']/div/div/div[2]/div/select</value>
      <webElementGuid>5e269ae5-00d3-484f-99ff-cd36deba9160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>3683c261-3943-4445-89de-ab16b1ef9fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'billingProviderIdentifierTypeCID' and @id = 'billingProviderIdentifierTypeCID' and (text() = '
     
NPI
Provider ID
' or . = '
     
NPI
Provider ID
')]</value>
      <webElementGuid>266e03ec-f104-4c99-b91a-55b7b5666f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
