<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>4796b3f6-6d16-4420-b757-cf200a758a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CancelButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CancelButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59e6b210-b5a4-439d-9311-0820cd87f698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>0735ea58-ef5b-4ef7-9cf3-171a4a9c812a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/mhYOY9fhqL4wWORAIJqTXmsSqyi/XWwCJXlu4z7Z1FwukYsdc8nTQtwFaDV11zLUXAbbYqP5Uo3pKgnB50P7aL5DAcm4LWdeqZ9XnsBQTOLEVlZI+q3fascL3EaqydbUrvHsP+C8DN0hbi5QF4j8uLOX9426pNvPPl6bKv27eAdd8E+1aknIsw==</value>
      <webElementGuid>60f83a3c-cee7-457a-965b-731ae590a56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CancelButton_ACTBUT</value>
      <webElementGuid>04d3e284-4ae7-4887-8e2e-b3ce854bdd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CancelButton</value>
      <webElementGuid>4c78a2fe-6a4c-4659-a051-b2953e823a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-remove-circle</value>
      <webElementGuid>68147f8e-2457-4f9f-8d55-446b4e3474f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return datalossConfirmationMessage('closeBtn');</value>
      <webElementGuid>e2e953a4-4af7-4bf8-96a9-8c15530ae4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>4bd9139d-8b82-489d-ba97-96c0be2c406b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>07730025-0070-4125-a6c9-1d5f30f573e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CancelButton&quot;)</value>
      <webElementGuid>054a5f9d-9cec-4569-9596-2d1538ba60e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CancelButton']</value>
      <webElementGuid>ed539ce2-706b-45a5-a936-28e85e24e92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgBtns']/div/button[2]</value>
      <webElementGuid>d8883363-9e44-4147-bb64-aa75c6681ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[1]</value>
      <webElementGuid>0b33a118-253b-4d9d-8e41-b284046ed1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BILLING ZIP CODE DOES NOT MATCH [evoBrix X] ENROLLMENT ZIP CODE'])[1]/following::button[2]</value>
      <webElementGuid>543f7cbb-c632-4879-9b66-d622bc7f3fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page ID: pgErrorCodeDetail(Claims)'])[1]/preceding::button[1]</value>
      <webElementGuid>b951d04f-bcbf-43ad-ba5b-c09c2ac974ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>c9583097-e37e-4eb0-8e99-858dea081aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f450163b-9207-42d8-9d25-c590254e2618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'CancelButton_ACTBUT' and @id = 'CancelButton' and @title = 'Cancel' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>61a6bac9-6718-4246-b28c-c231b90b972b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
