<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_to extend your session by 30 minutes_t_89a459</name>
   <tag></tag>
   <elementGuidId>30bb74ed-81c4-4cf6-9448-1fcbb9117cbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.top-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='scrollup']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52360bee-895e-4ffc-bbf4-dd0c28fd7bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-image</value>
      <webElementGuid>5517959e-c851-42b2-86a4-6852ee1f0777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollup&quot;)/span[@class=&quot;top-image&quot;]</value>
      <webElementGuid>10a3b6c8-33e8-491f-b1c4-4f408a01bd6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='scrollup']/span</value>
      <webElementGuid>ab1e74fd-7225-47c3-8f59-52c502e45fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>569c2f78-46cc-48c7-ba52-95bd3833050a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
