<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>9952af19-8a46-4e97-9e4c-a66668c42fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CloseButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CloseButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>165cafd1-4e8a-4243-8fe6-fc146a92b2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>4f324911-ef73-4bff-a6d5-3a9215871038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/CFCkql7N8RNIXvCRN/TfjCkMTI7m49nD0dIRznyWWSR+zkRCi2kOqCTB0SVyK3JyGttd3DERMa5/s60R4JT7Tdxl4TiT5+jYF1XJaHKXjL01SWscg/OVtT9Xdy0b/as2pOylqO0jlt1WEpzQMSyax9Xq0RrhSIzOlRxLjuIfdxh8XmbvStrSb4oPdjka4sVkrc56p+tYxAH+dyYgrUVgTwaXMuyFihCr3ooCMWEnsxUbDYls2i36Ktz4Uze1HD53pGsJFxWBpsOqzDmzvAgMbNgObcClRYILKPhLqtAnIHBj6tVqfbwy1DCyDmhxIz256q25ubjEvm7YZJAT4OK1LuPNXTRqDRQeAB6ROOVMHAImG1QqT1zG+eqUlp7HWzCN7aLBFq/tiGJjpJZxHjz8Lwtg37gCDnKEbKWlXkoUGtNjkzTK3GyGh6eRGHHiSCJ/+nCbsyq551Q=</value>
      <webElementGuid>060056e6-c3be-4a1f-9310-2335e62ba067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CloseButton_ACTBUT</value>
      <webElementGuid>22164f97-8dd2-47d7-9e47-1c199529028c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CloseButton</value>
      <webElementGuid>d2e23a40-6956-4c4c-96ac-6355b5f0aaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-remove-circle</value>
      <webElementGuid>d85e4d10-5e5b-41a0-9f6e-bdb075587358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return datalossConfirmationMessage('closeBtn');</value>
      <webElementGuid>47eae794-0ea8-47c2-a5d8-cd3e96c257d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>76ec195e-3d08-476a-ac5c-cf09b8a880d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>2a96ac54-d783-46b0-bdb1-a3c1f956551f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CloseButton&quot;)</value>
      <webElementGuid>0e6ce2ac-8130-4a76-bb2b-8b90efde1e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CloseButton']</value>
      <webElementGuid>698eba49-db59-4943-88d9-8895b1cc3343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dlgbtns']/div/button</value>
      <webElementGuid>2278c974-d4ba-4ede-afac-13891f3fe4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Records Found!'])[3]/following::button[1]</value>
      <webElementGuid>ba48700e-20fc-4153-b71d-05dcc1467b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='activate to sort'])[36]/following::button[1]</value>
      <webElementGuid>26330bac-1f98-4915-afd6-3ca619871bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[2]/preceding::button[1]</value>
      <webElementGuid>84e83852-5bed-4286-8e54-f78a6cfff810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page ID: pgDiagnosisSummary(Reference)'])[1]/preceding::button[2]</value>
      <webElementGuid>e7e5b87e-b6b4-46d9-bd6c-6a51fc15f6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>7099d825-8faa-4810-a6c7-71fc12a50386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[7]/div/button</value>
      <webElementGuid>66a4f6ac-54ec-4e81-9081-237e4f4da92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'CloseButton_ACTBUT' and @id = 'CloseButton' and @title = 'Cancel' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>4355c69c-2f8a-438e-9f25-28fb8bd13a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
