<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1</name>
   <tag></tag>
   <elementGuidId>20130a9f-d852-44ef-934c-b8e346a5e210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-2.col-md-2.col-sm-2.cust-control-label.fontsize12px > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmResolveClaimHeaderDetail']/div/div[2]/div/div[3]/div/div[8]/div/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76a0eb1e-2128-4dae-8b35-0464c53af4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>JavaScript:gotoLinkPage('pgDiagnosisSummary','8353514950526565');</value>
      <webElementGuid>3d95b062-77bc-4312-98b6-7016212fd82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc6fd89a-0632-4c0a-b717-d61a613db3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmResolveClaimHeaderDetail&quot;)/div[@class=&quot;widget-box&quot;]/div[@class=&quot;widget-content margin-top5px&quot;]/div[1]/div[@class=&quot;row margin-x0px pad-bottom5px&quot;]/div[@class=&quot;row margin-x0px&quot;]/div[@class=&quot;row margin-x0px margin-bottom5px&quot;]/div[@class=&quot;col-lg-8 col-md-8 col-sm-8 col-xs-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-lg-9 col-md-9 col-sm-9&quot;]/div[@class=&quot;col-lg-3 col-md-3 col-sm-3&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-lg-2 col-md-2 col-sm-2 cust-control-label fontsize12px&quot;]/a[1]</value>
      <webElementGuid>2b769a3d-c185-45b8-ac33-ccb5d5b1c8db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmResolveClaimHeaderDetail']/div/div[2]/div/div[3]/div/div[8]/div/div/div/div/div/div/a</value>
      <webElementGuid>61c72313-43b3-4510-8fab-0462f7f128b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'1')])[21]</value>
      <webElementGuid>c7aa85d2-9c3f-4a32-a414-bcacd7384277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;JavaScript:gotoLinkPage('pgDiagnosisSummary','8353514950526565');&quot;)]</value>
      <webElementGuid>81016a60-42a8-4cbd-8fe8-2c6ef14bdedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div/a</value>
      <webElementGuid>d3b7feda-51c5-4e3a-bca8-06e98d6faa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;JavaScript:gotoLinkPage(&quot; , &quot;'&quot; , &quot;pgDiagnosisSummary&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;8353514950526565&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = '1' or . = '1')]</value>
      <webElementGuid>aeb9f54b-9a4c-450e-a894-1ae7e06a4196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
