<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_212229010000018000</name>
   <tag></tag>
   <elementGuidId>36461a23-aac5-449e-ae5e-a575db40e6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;navigate('/jlOLwuHdiymbGOzgqDjdn6vSv7NfOSWdPoCE7B8WWLIQYH0QVtxa3NUieTLhB9UDNlijNJYmAWIN+B896Ni7lawaRijIq2fWZLv6YIMv8/PFad0TH9mOCHH2syT0SeXd2hbyw2NtSlg=','212229010000018000~1590132868~0')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8683b53-4f7d-4e35-9a1f-4fdb8362f1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>380ad4db-b757-451a-8c4c-b9d87d10a42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>navigate('/jlOLwuHdiymbGOzgqDjdn6vSv7NfOSWdPoCE7B8WWLIQYH0QVtxa3NUieTLhB9UDNlijNJYmAWIN+B896Ni7lawaRijIq2fWZLv6YIMv8/PFad0TH9mOCHH2syT0SeXd2hbyw2NtSlg=','212229010000018000~1590132868~0')</value>
      <webElementGuid>576a7461-9ab3-4535-b495-d335c8a8cba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>f7497a97-da25-47f2-ad20-b072e7b043af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-champs-tooltip</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>6b30d61e-7bb6-4063-9f39-d01b6a3c4df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Claim Header or Line Detail</value>
      <webElementGuid>4a2bcb03-e1d9-4c94-b396-5aac20ad3982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>212229010000018000</value>
      <webElementGuid>9566e6f1-fe34-45e9-8bd3-bfe264635804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dlgViewClaimHeaderDetail_Grid1_tbrow&quot;)/tbody[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>3ba43fd9-4303-48b7-9264-34a04e667d49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;navigate('/jlOLwuHdiymbGOzgqDjdn6vSv7NfOSWdPoCE7B8WWLIQYH0QVtxa3NUieTLhB9UDNlijNJYmAWIN+B896Ni7lawaRijIq2fWZLv6YIMv8/PFad0TH9mOCHH2syT0SeXd2hbyw2NtSlg=','212229010000018000~1590132868~0')&quot;]</value>
      <webElementGuid>5b33c763-67b1-4038-bc8e-bd3708e57eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dlgViewClaimHeaderDetail_Grid1_tbrow']/tbody/tr/td/a</value>
      <webElementGuid>d5c6efe3-9fed-4511-8f12-e57a4a853a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'212229010000018000')]</value>
      <webElementGuid>e2cc01b0-41e7-49c1-bb11-5dd5fec4bd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='activate to sort'])[8]/following::a[3]</value>
      <webElementGuid>fd8923d5-2bb1-4551-9865-a15d8e0c9e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Header or Line Detail'])[1]/preceding::a[1]</value>
      <webElementGuid>ddc60338-b786-4dcc-b73d-50e2a840b70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBMITTED GENDER DOES NOT MATCH ELIGIBILITY'])[1]/preceding::a[2]</value>
      <webElementGuid>089b014b-e573-4e8c-9d1f-7c9ec2e0fb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='212229010000018000']/parent::*</value>
      <webElementGuid>48ca53f2-ec1b-4782-af10-ff13cb661dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[43]</value>
      <webElementGuid>894c5a22-e38e-4153-81fb-25b00439b18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>3d60508f-fcfe-4dcd-b433-67014152d3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '212229010000018000' or . = '212229010000018000')]</value>
      <webElementGuid>6da59099-3ebd-422b-95a8-e192aba3394e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
