<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5107</name>
   <tag></tag>
   <elementGuidId>5f8de934-6514-4cb2-b139-819fe803e483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;inquireClmNavigation('/5dk40CMrQXqYDRzTxh9rkPuvY96XZMmWgROU6I/0h8mV6ChEyOfpws/AHXnMTB/MbPZRBzqgHOZBla30fFPqR3oUn1oXYTstIXrJDm336Kkps9hdxJj8hQ==','75004092~75005012')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>391afcd9-2f91-48da-84c0-b4ebbf3fb835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d487074b-dd01-4752-ae2b-69354a7dfefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>inquireClmNavigation('/5dk40CMrQXqYDRzTxh9rkPuvY96XZMmWgROU6I/0h8mV6ChEyOfpws/AHXnMTB/MbPZRBzqgHOZBla30fFPqR3oUn1oXYTstIXrJDm336Kkps9hdxJj8hQ==','75004092~75005012')</value>
      <webElementGuid>e9b35a4b-f3c8-4b90-acf2-34f321a646e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>44fd8104-f6a9-44c8-af64-e30a6f24e22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-champs-tooltip</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>fe22aba1-ce97-44c7-84ae-2e2e47b6904e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>ErrorCodeDetail</value>
      <webElementGuid>09b646bd-9f02-4d30-9210-07be3bfaef2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5107</value>
      <webElementGuid>13664fac-d858-4834-803b-7be0ebf9ff84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dlgViewClaimHeaderDetail_Grid1_tbrow&quot;)/tbody[1]/tr[7]/td[2]/a[1]</value>
      <webElementGuid>23f85811-b945-4da6-8f81-96258f36eca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;inquireClmNavigation('/5dk40CMrQXqYDRzTxh9rkPuvY96XZMmWgROU6I/0h8mV6ChEyOfpws/AHXnMTB/MbPZRBzqgHOZBla30fFPqR3oUn1oXYTstIXrJDm336Kkps9hdxJj8hQ==','75004092~75005012')&quot;]</value>
      <webElementGuid>3eacf72e-fb4a-4d46-b1ac-a1ece6763f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dlgViewClaimHeaderDetail_Grid1_tbrow']/tbody/tr[7]/td[2]/a</value>
      <webElementGuid>968bc0b6-6f5f-4e41-9429-dac86973b6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'5107')]</value>
      <webElementGuid>e92e93c5-4ae9-4869-8792-1ae97d5a6d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[6]/following::a[2]</value>
      <webElementGuid>bb267290-8637-4d74-9760-dd0b076181a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ignore'])[2]/following::a[2]</value>
      <webElementGuid>13525cb1-ddec-4b27-97ca-c9489b7e3fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ErrorCodeDetail'])[1]/preceding::a[1]</value>
      <webElementGuid>d29c8911-efda-49ad-95b0-99e6665bc722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BILLING ZIP CODE DOES NOT MATCH [evoBrix X] ENROLLMENT ZIP CODE'])[1]/preceding::a[1]</value>
      <webElementGuid>a7d2fec3-03df-4dfc-a363-037d43fd8762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5107']/parent::*</value>
      <webElementGuid>1f7954ba-f23d-4a30-8208-0a0b80b9d3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[56]</value>
      <webElementGuid>161e818d-b4a9-4d70-9ad2-20865110be1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/a</value>
      <webElementGuid>11b203c6-4e85-4a98-85d1-96af07fdb60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '5107' or . = '5107')]</value>
      <webElementGuid>976ea826-d785-4d07-b4a5-996d630cd2e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
