<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>c02a51ca-1fa5-4f06-a3c1-aa86b3a4319e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CancelButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CancelButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2f4496e-fe7f-4b27-a210-857b840582a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>a7805b50-b94a-4a11-aa69-703baee7eae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/yBCsbLInLRiyeu4EU1/pkSJYYTNvhgAIo440wcrvtXbrCSdooATsBZlCQaIrN3EyEo23+mQC6pNIeChMMnpoC+NjTx5qOWzd</value>
      <webElementGuid>8c6a2796-f121-4a7a-ba6a-239bfd57009f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CancelButton_ACTBUT</value>
      <webElementGuid>26e8d2c7-8d79-4b68-b19e-2763ec3dd360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CancelButton</value>
      <webElementGuid>a8a1ce7c-4be0-45d1-9c45-47e42b5b56c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-remove-circle</value>
      <webElementGuid>4415c7fd-e0cb-44fd-ba2d-04ffb7eee51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return datalossConfirmationMessage('closeBtn');</value>
      <webElementGuid>0859eceb-a648-4eb3-956b-197fa810ac33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>4e0e25d0-277f-4c4e-812d-55fc7b241513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>24b09b6e-0cb8-4386-a677-0fd0ff70eb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CancelButton&quot;)</value>
      <webElementGuid>df752b78-ebc2-4858-b2df-6dc52af3620c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CancelButton']</value>
      <webElementGuid>62489750-60ba-4d3a-b1a0-bd60c44b9b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dlgbtns']/div/button</value>
      <webElementGuid>be96149d-fbec-4342-be5d-3fc3a727183e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dlgClaimViewHeaderDetail'])[1]/following::button[1]</value>
      <webElementGuid>d44d29a7-3011-4051-9b4a-ba0d8778e3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAInquireRes'])[1]/following::button[2]</value>
      <webElementGuid>d4916d5a-043b-4c5e-bc0c-7bd38ab21509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[2]/preceding::button[1]</value>
      <webElementGuid>235d31c5-69db-49d3-8a86-b0f125c16c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page ID: dlgViewClaimHeaderDetail(Claims)'])[1]/preceding::button[2]</value>
      <webElementGuid>4472c8ff-3552-45e5-bc7c-2a6741519359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>9ed8d631-d523-48ea-a4ed-7796d5a1767d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>3bba11f4-e485-45d9-a32c-ceadd283927f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'CancelButton_ACTBUT' and @id = 'CancelButton' and @title = 'Cancel' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>d214ad80-4eef-4358-bb01-38108d737ec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
