<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_212229110000054000</name>
   <tag></tag>
   <elementGuidId>fef894d5-d38c-46d4-9ea9-dadd2a8d8da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;inquireClmNavigation('/p1FPBG/IfWOlNEvrPu9hEO6SwjDXLyXlrZWIGXA7c+A1IQZ6oZ4QnoHhkOj5cPYM0BITOJcyImIpCBXjmD4RuOjN+DH95dRvIcTVHjmewJ5TTZlglByOnbgPVt/f0TJlZ+N/MWkGRbK0EY+z4PtXm1vYNQnOlLFC','1590134001~212229110000054000~72~~N~A~P')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81d6496f-5796-41a8-9474-81c817b10f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0cc9eb72-40e0-4055-9b00-77631ef477d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>inquireClmNavigation('/p1FPBG/IfWOlNEvrPu9hEO6SwjDXLyXlrZWIGXA7c+A1IQZ6oZ4QnoHhkOj5cPYM0BITOJcyImIpCBXjmD4RuOjN+DH95dRvIcTVHjmewJ5TTZlglByOnbgPVt/f0TJlZ+N/MWkGRbK0EY+z4PtXm1vYNQnOlLFC','1590134001~212229110000054000~72~~N~A~P')</value>
      <webElementGuid>f2c1d1a9-ba7f-46e4-be7a-ced1ada94094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>4812d6c7-d394-409d-b059-98650eeb50d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-champs-tooltip</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>01853dd0-08eb-4d3a-8820-4a1e6486be36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Claim Header Detail</value>
      <webElementGuid>31bccb6d-b746-46e4-abde-ae46bd2edb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>212229110000054000</value>
      <webElementGuid>5707cad5-2f25-4ff1-b85e-5b7af1be9dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgInquireClaimsStateList_Grid1_tbrow&quot;)/tbody[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>68d462d8-5463-4a1b-92dd-e84d3db77cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;inquireClmNavigation('/p1FPBG/IfWOlNEvrPu9hEO6SwjDXLyXlrZWIGXA7c+A1IQZ6oZ4QnoHhkOj5cPYM0BITOJcyImIpCBXjmD4RuOjN+DH95dRvIcTVHjmewJ5TTZlglByOnbgPVt/f0TJlZ+N/MWkGRbK0EY+z4PtXm1vYNQnOlLFC','1590134001~212229110000054000~72~~N~A~P')&quot;]</value>
      <webElementGuid>cd743a49-2a4d-4e95-b08f-faf999cd7780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pgInquireClaimsStateList_Grid1_tbrow']/tbody/tr/td/a</value>
      <webElementGuid>58d0f17d-c794-48d5-b7e0-ec15e006dd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'212229110000054000')]</value>
      <webElementGuid>822ac67f-73c7-40d2-a726-16b2955686a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='activate to sort'])[10]/following::a[3]</value>
      <webElementGuid>c24200d5-d5e3-42c7-9795-85e580ea4e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Header Detail'])[1]/preceding::a[1]</value>
      <webElementGuid>bd9e2508-4003-41fc-aa4c-352710b1ff5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J-Professional'])[1]/preceding::a[1]</value>
      <webElementGuid>25d8dcbd-074d-4bc0-927c-92d46cec9c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='212229110000054000']/parent::*</value>
      <webElementGuid>fd99a37f-352e-44c7-a30e-f7abe2f38231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[606]</value>
      <webElementGuid>ce975d8a-700e-4d00-beb4-7065ec79019a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>8e475045-2c06-4021-a56e-93cfa29291fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '212229110000054000' or . = '212229110000054000')]</value>
      <webElementGuid>b16968ba-329e-46c5-85f5-c612e72003cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
