<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_212229010000018000</name>
   <tag></tag>
   <elementGuidId>cde10207-3824-4cee-a83f-ae9a3df7ab21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;inquireClmNavigation('/KLun7bJ9YGoDgvYPhxMfSqRz8UKM3J3JoQ3PZDXPrFehxlMvFVzFqJODdhfNy/oc9ELOOgDyqoRP66dng+IqCjF8qQFZFeLt1aF+gnoOgK9XC8z2hA18CDKPd+IJaYxCqNwDVQdvsrW5A3BHjQeT1GmID6Vjk/+J','1590132868~212229010000018000~72~~N~A~P')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35a3f100-cc6a-450e-bbfd-f393083bfe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cd60927a-03da-4099-a43c-a8466c999eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>inquireClmNavigation('/KLun7bJ9YGoDgvYPhxMfSqRz8UKM3J3JoQ3PZDXPrFehxlMvFVzFqJODdhfNy/oc9ELOOgDyqoRP66dng+IqCjF8qQFZFeLt1aF+gnoOgK9XC8z2hA18CDKPd+IJaYxCqNwDVQdvsrW5A3BHjQeT1GmID6Vjk/+J','1590132868~212229010000018000~72~~N~A~P')</value>
      <webElementGuid>a1e9cd62-3ae2-4417-b1c3-480718dcf1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>0d95aed2-62d7-4c0c-8fe9-77de7bf86695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-champs-tooltip</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>06b0cbd1-bb06-43df-aa7a-47fb61902df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Claim Header Detail</value>
      <webElementGuid>ef734f9a-d304-4078-b3aa-6d2f5acff432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>212229010000018000</value>
      <webElementGuid>f02ab8eb-3e59-4c20-8af5-b0b729b8788e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgInquireClaimsStateList_Grid1_tbrow&quot;)/tbody[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>044de4b4-5d52-4074-a015-71e44c97cc9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;inquireClmNavigation('/KLun7bJ9YGoDgvYPhxMfSqRz8UKM3J3JoQ3PZDXPrFehxlMvFVzFqJODdhfNy/oc9ELOOgDyqoRP66dng+IqCjF8qQFZFeLt1aF+gnoOgK9XC8z2hA18CDKPd+IJaYxCqNwDVQdvsrW5A3BHjQeT1GmID6Vjk/+J','1590132868~212229010000018000~72~~N~A~P')&quot;]</value>
      <webElementGuid>595a8717-727c-47bc-94fb-189a5906e197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pgInquireClaimsStateList_Grid1_tbrow']/tbody/tr/td/a</value>
      <webElementGuid>ba29fe16-a998-4bb8-ae13-342e3e5993cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'212229010000018000')]</value>
      <webElementGuid>7240a7a0-b11d-4e23-86bf-b5995da9fb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='activate to sort'])[10]/following::a[3]</value>
      <webElementGuid>559ba3b4-a798-47d8-a6de-581fd740a105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Header Detail'])[1]/preceding::a[1]</value>
      <webElementGuid>f663a9ca-abfb-444d-b36f-8bc72a43e65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J-Professional'])[1]/preceding::a[1]</value>
      <webElementGuid>30b68664-7aac-49f4-a1e7-5679229ccf7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='212229010000018000']/parent::*</value>
      <webElementGuid>4e124543-cd7a-4fb7-9ee9-d1cdf1cee3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[606]</value>
      <webElementGuid>bc141000-aab4-4cbb-89de-9e34f13f8599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>bd6481ae-9431-4ccd-baf9-4bf7da90267d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '212229010000018000' or . = '212229010000018000')]</value>
      <webElementGuid>801c8d2b-7ed5-4aab-8804-52912f8b7c4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
