<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Inquire Claims_pgInquireClaimsStateLi_d54022</name>
   <tag></tag>
   <elementGuidId>cd046d9f-077d-4220-beed-334dcf857152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgInquireClaimsStateList_Filter1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pgInquireClaimsStateList_Filter1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1070ea6-e539-4478-a195-579b68e7a537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>a94c3e61-8a71-416a-b949-87c742358c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgInquireClaimsStateList_Filter1_1</value>
      <webElementGuid>085a038e-79cf-40f9-a710-6a80e7028a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgInquireClaimsStateList_Filter1_1</value>
      <webElementGuid>92249b0e-4529-4c82-a2f5-e42a62abea83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>enterSubmitForFilter(event,this)</value>
      <webElementGuid>2d3993d0-baa7-4a58-ab8b-03714c308e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return enterSubmitForFilter(event,this,'pgInquireClaimsStateList_Grid1');</value>
      <webElementGuid>cef08a5e-f638-4cdf-856d-600c9d3adb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fcb26419-b8f8-4d98-8d48-746b0f836f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputTextSmall list-filter</value>
      <webElementGuid>9326a32b-e193-4f2c-8ea1-38ab85b2a792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Filter Value1</value>
      <webElementGuid>96702d16-9b63-4fd3-978e-aa30e042b623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a3068ade-37e6-4b7d-9ca6-32a7994d5db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pgInquireClaimsStateList_Filter1_1</value>
      <webElementGuid>4babfb0f-c76f-4e7e-bb74-c3356085d32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>pgInquireClaimsStateList_Filter1_1</value>
      <webElementGuid>db865ef5-f993-46b1-aee0-786bea645af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgInquireClaimsStateList_Filter1_1&quot;)</value>
      <webElementGuid>8dd48364-442c-4bf8-a84e-5e09830865d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pgInquireClaimsStateList_Filter1_1']</value>
      <webElementGuid>8c2ee3c7-d447-4078-aead-52fa02067be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgInquireClaimsStateList_Grid1_filter']/div[2]/input</value>
      <webElementGuid>3d46f371-c0b4-449b-903d-6a8b934b314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>f1e13445-3ce1-4eae-be35-d30fa77ec649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'pgInquireClaimsStateList_Filter1_1' and @name = 'pgInquireClaimsStateList_Filter1_1' and @alt = 'pgInquireClaimsStateList_Filter1_1']</value>
      <webElementGuid>f3ded3df-1231-4dff-a647-a01a00be6c05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
