<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_In_pgInquireClaimsStateList_Grid1_GoButton</name>
   <tag></tag>
   <elementGuidId>9d24aeaa-4f4d-4943-a927-ff44bdb82e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgInquireClaimsStateList_Grid1_GoButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pgInquireClaimsStateList_Grid1_GoButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcf20e7f-15a1-4a7e-9ba5-a72c85bdefa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>BUTTON</value>
      <webElementGuid>50e5b0e5-16c5-4248-839b-cf95fe7a39a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgInquireClaimsStateList_Grid1_GoButton</value>
      <webElementGuid>8c6e98b8-3673-41c4-8d61-48b848e2fdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgInquireClaimsStateList_Grid1_GoButton</value>
      <webElementGuid>2cc9d9da-47b1-4248-b1a0-a923a0199314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>bf6ad658-162c-49d0-99e6-6455bd6ad4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>406e4a5d-5cc7-4b4c-992e-1cad49bab8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>goButton('/ld6gk6hvuW03n+LlfRAZJDv3ZTVtOyZJKeUHWkSjxf6RefzR3ID9YLjKLdJGxh/H00gRY0VyTaslaDxKgtlc81gMZPNuYkCmxvqoSYR4Orglsdrb8lkY0nkCXY0tOXqDmcqeB32QNPFSZL7Lu8m2ZIRKTt444fRLwKJOCO1I5A1bhcuSUmOxdg==','pgInquireClaimsStateList_Grid1');</value>
      <webElementGuid>d0f6e2a1-d72d-43c2-ac78-1d9d8e71a1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn i-icon i-icon-play-circle </value>
      <webElementGuid>96edaaee-0503-4566-ac74-b5bec18893d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>NOT-DEFINED-PGC</value>
      <webElementGuid>3ce4e256-2210-45c0-9f1b-4149269d23e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Inquire Claims Filter Go</value>
      <webElementGuid>4cb4cd11-efb9-401c-9662-ad9cb7a27d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Inquire Claims filter Go </value>
      <webElementGuid>2e133414-9cab-46ad-88b9-5f08ecb8bc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgInquireClaimsStateList_Grid1_GoButton&quot;)</value>
      <webElementGuid>e0de4d2e-2161-4e48-a535-bf569b0cabf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pgInquireClaimsStateList_Grid1_GoButton']</value>
      <webElementGuid>5e607fcd-968f-4bf5-86a3-ab805fdf1e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgInquireClaimsStateList_Grid1_filter']/div[22]/input</value>
      <webElementGuid>4d5f90e0-9736-4410-be3a-65646a1340e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/input</value>
      <webElementGuid>4e77a6d3-b368-493f-b699-2aab1dc7106a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'BUTTON' and @id = 'pgInquireClaimsStateList_Grid1_GoButton' and @name = 'pgInquireClaimsStateList_Grid1_GoButton' and @title = 'Inquire Claims Filter Go']</value>
      <webElementGuid>1ddc947a-5a3d-4f1a-bb54-525ce07243da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
