<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_000000</name>
   <tag></tag>
   <elementGuidId>b22bfa58-5346-4e70-9ec6-64613eead11b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pgProcedureList_Grid1_tbrow']/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>619f7575-8bd9-4fc6-b586-2e47548e9f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c36da76f-0170-4794-b29a-cfdf24b1c231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>navigate('/DGRAObiKVr3luE6TBvHpt74H0QypTv+KNzMqKz3pbAY84aSL1f19aJ+Y4OyH0cHISzgYOiktyyf0jOOt4gm2HbvpmSIEZ9ZKrmFHbSH+/NiHb9/wq4VWMZmAEr+NhVUpzKrLRQso0rE=','000000~48484848484880~75181595')</value>
      <webElementGuid>ade28a07-a83e-4946-bef8-7da720569276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>5a735774-eb06-4ef9-a2a3-c899b3180fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-champs-tooltip</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>63745415-25ad-4df7-a5a5-38cc76eae22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Procedure Details</value>
      <webElementGuid>20eee9bc-b2e8-4619-9f7b-7ff30a130613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>000000</value>
      <webElementGuid>5044b2c9-8e2f-4dc1-bb5c-f8c18e77b756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgProcedureList_Grid1_tbrow&quot;)/tbody[1]/tr[1]/td[2]/a[1]</value>
      <webElementGuid>90e5658b-86cc-49d2-af32-45dc54fe75c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;navigate('/DGRAObiKVr3luE6TBvHpt74H0QypTv+KNzMqKz3pbAY84aSL1f19aJ+Y4OyH0cHISzgYOiktyyf0jOOt4gm2HbvpmSIEZ9ZKrmFHbSH+/NiHb9/wq4VWMZmAEr+NhVUpzKrLRQso0rE=','000000~48484848484880~75181595')&quot;]</value>
      <webElementGuid>684514c4-268b-47ee-bfcd-6ccdd1ad3cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pgProcedureList_Grid1_tbrow']/tbody/tr/td[2]/a</value>
      <webElementGuid>07f8b306-1cc1-4806-b6f8-3b617ec8fea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'000000')]</value>
      <webElementGuid>fe84a56d-5b1b-4919-9517-0b91b11d588f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='activate to sort'])[6]/following::a[3]</value>
      <webElementGuid>40d68166-60dc-4e49-ba62-ce5f5ac919ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedure Details'])[1]/preceding::a[1]</value>
      <webElementGuid>73911a5c-a523-48ea-99bc-a8866223a8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sds'])[1]/preceding::a[1]</value>
      <webElementGuid>a6aebeb2-b1b5-4a66-920e-d772bc72d4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='000000']/parent::*</value>
      <webElementGuid>247d5e5f-1777-49c1-ac68-be7c82691535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[598]</value>
      <webElementGuid>baa3b793-87df-4489-be15-73f0527d0c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>b1e3e3a5-7fce-4ff5-bcfc-d7fd78d7e2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '000000' or . = '000000')]</value>
      <webElementGuid>ae556905-f4d2-4449-b906-9894da87b4f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
