<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1AQA5</name>
   <tag></tag>
   <elementGuidId>967e138d-f987-40e8-8436-99273d61dadc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;navigate('/ZHQ+erG7CfGFR+y7DGwYuZ/oldDAAiJ65gkMkoqI7JOZ9PNpmkiPMte6kZ5FMLr0NIVgYPcBfgpiRTMMNJ4v72d7Gx8ox0oYGK97HILYHOgKC+gVSAn6XSXHUK9o5iEt','1AQA5~496581655380~75190031')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f00f772-6606-450b-a08c-96223be6989f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ddfb7b60-eb13-4199-afae-85b4dbeea045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>navigate('/ZHQ+erG7CfGFR+y7DGwYuZ/oldDAAiJ65gkMkoqI7JOZ9PNpmkiPMte6kZ5FMLr0NIVgYPcBfgpiRTMMNJ4v72d7Gx8ox0oYGK97HILYHOgKC+gVSAn6XSXHUK9o5iEt','1AQA5~496581655380~75190031')</value>
      <webElementGuid>8b88d2fc-c4b3-497f-8c02-246365ccb037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>9ecc2824-c23c-4ae9-b651-a2f2cea6b7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-champs-tooltip</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>99d21259-f8b5-4db2-ae0a-5e9a9c634192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Procedure Details</value>
      <webElementGuid>9702680b-2c69-4461-88f0-bfab8c8b79e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1AQA5</value>
      <webElementGuid>d8afeb4b-97fc-44a5-a067-a6528123eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgProcedureList_Grid1_tbrow&quot;)/tbody[1]/tr[1]/td[2]/a[1]</value>
      <webElementGuid>1f59fa64-cab4-4f6c-86cb-6e5397134127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;navigate('/ZHQ+erG7CfGFR+y7DGwYuZ/oldDAAiJ65gkMkoqI7JOZ9PNpmkiPMte6kZ5FMLr0NIVgYPcBfgpiRTMMNJ4v72d7Gx8ox0oYGK97HILYHOgKC+gVSAn6XSXHUK9o5iEt','1AQA5~496581655380~75190031')&quot;]</value>
      <webElementGuid>3d740725-679b-4ebb-a319-4e4dafb1f98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pgProcedureList_Grid1_tbrow']/tbody/tr/td[2]/a</value>
      <webElementGuid>12e8305e-fa5a-45cb-97fc-744693df7eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1AQA5')]</value>
      <webElementGuid>d4783651-a9ba-42c6-bd33-8a0ce7ad6614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='activate to sort'])[6]/following::a[3]</value>
      <webElementGuid>ee62e1ad-965a-42f1-9acb-9f43d6475add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedure Details'])[1]/preceding::a[1]</value>
      <webElementGuid>34e99cd0-0d93-4db7-8bae-7d9c2065e9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST'])[1]/preceding::a[1]</value>
      <webElementGuid>b1a001ea-b76d-48c2-bd01-f9cbc6bf58c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1AQA5']/parent::*</value>
      <webElementGuid>8ad7550c-98bf-44f5-96e8-20d751e84793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[588]</value>
      <webElementGuid>1278ff99-41ab-4e0b-ad1e-e3482285e468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>b7352a3b-d254-47e8-a8db-d62d7f6a4807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '1AQA5' or . = '1AQA5')]</value>
      <webElementGuid>96d8e856-ba9b-4c8c-8e9e-d5fd58cdc6d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
