<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>2e3bccae-e0ca-47c2-8ae8-073462b7b85a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>215c95f1-e967-44ce-90f2-45ec899273ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>44b48709-944b-4505-a4a6-cb8b10c6aace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/EVzU82Ni7/3ojNGzLeIKDOPhmH98EhyvjmjI5RYKPluUzBBhL9VT1ki/gfoDwp6XKd10mbA33Nus6LRLgn1qfL2rtJYrzNkmedVaWtmFlcCEl7Ee4Le7/vMyUKUCFcESP1+SE/BSHZnHNbeXgEt+t1bfm1YCE7hP5cFI2uLl6TNUtgMNR9FAO+NjzilWFX15+rQqVGCf3ACit9XpSEPqZXzZmR4Mk/1C0owv5DkRtKcIs6a+kZQHzBi40ZvVLgfk7O0WO4yG9T5aDQNO3Isfu+JvAaDY0W0RhPNcd08+Y2AIKc23WNi2Hadav0Axu8UupYb+FIJNSOOa2vCuOoIQgdYsDoz0IsQhSqAV51OhL+A=</value>
      <webElementGuid>495fea73-c436-4a4b-adb6-526d4937eaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Add_ACTBUT</value>
      <webElementGuid>73522431-1564-47ef-bf9a-ad9d9b35f593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>f8b86ed8-dc6a-4803-bf1d-e700a7a816b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn btn-mini i-icon i-icon-plus-sign</value>
      <webElementGuid>d7d71681-aeaa-4f78-8454-ce911754ce89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return frmSubmitToDialogPage(this,950,800);</value>
      <webElementGuid>efa1478e-7225-44b4-afbd-3bd1ec7c3140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>449ad029-adfc-496d-b853-04eb6cf848d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>fea9ff2e-a517-4363-b892-3222935ef623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Add&quot;)</value>
      <webElementGuid>60204cbb-3390-44c7-864d-47e61885ed4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Add']</value>
      <webElementGuid>13d6bb90-318d-4af8-9de4-ad5f54568c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridBtns']/div/button[2]</value>
      <webElementGuid>f5d75292-3a45-46b7-9f0e-5a7bd2ba258a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::button[1]</value>
      <webElementGuid>49063268-ad25-4cd1-8e49-e5f699e1acd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::button[2]</value>
      <webElementGuid>63bf17b6-032c-45c7-8f65-02f97a6a4c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/preceding::button[1]</value>
      <webElementGuid>7d307600-01f1-4139-b7bc-f735e98549f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/preceding::button[2]</value>
      <webElementGuid>b47be686-3441-4008-845c-4852ff09b011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>b9bfcd66-1580-4e73-ade9-abff71c05081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>6a7fda79-f415-402a-9120-4acbfed9741f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'Submit' and @name = 'Add_ACTBUT' and @id = 'Add' and @title = 'Add' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>71a0169a-a618-4318-a0dd-20e3f7eb878a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
