<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Procedure Code_pgProcedureList_Filter1_1</name>
   <tag></tag>
   <elementGuidId>afe4e8c7-3f85-4449-acd5-128bc373af07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgProcedureList_Filter1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pgProcedureList_Filter1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9307bdb5-ca0b-4841-a532-de6907ba0b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>5fbfd740-54f4-4a3c-9b57-29eae046e36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgProcedureList_Filter1_1</value>
      <webElementGuid>496aedbb-dfd4-4ad4-9e00-b9728c92b81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgProcedureList_Filter1_1</value>
      <webElementGuid>94d39c16-b12c-4b4f-b0f7-fb6d66ec252e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>enterSubmitForFilter(event,this)</value>
      <webElementGuid>2b96dc27-31fa-465c-805a-4e3d0fc5a1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return enterSubmitForFilter(event,this,'pgProcedureList_Grid1');</value>
      <webElementGuid>ac21a969-a5b7-4517-a9fa-be5023b709df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af869887-05ea-4067-8efb-194b3bbc533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control list-filter</value>
      <webElementGuid>e1cda99a-93c4-4a8d-ae8a-36a0e1d52112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>Filter Value1</value>
      <webElementGuid>8f5ec1e1-5a27-4bd8-bf61-b4cea69c2c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b3693418-9183-423b-8110-fa6c6367ce8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pgProcedureList_Filter1_1</value>
      <webElementGuid>9c3c4e42-b45c-47d1-ad63-ff1b60c2de26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>pgProcedureList_Filter1_1</value>
      <webElementGuid>651ff30b-261b-4565-b234-b09abe2071a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgProcedureList_Filter1_1&quot;)</value>
      <webElementGuid>19a6d838-07e0-4b60-963e-329ab75fd99d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pgProcedureList_Filter1_1']</value>
      <webElementGuid>6ea509d3-3771-4cb6-bc55-027157d75a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgProcedureList_Grid1_filter']/div[2]/input</value>
      <webElementGuid>baa8f902-10d2-455a-8c1d-a18f30c38db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2da6c488-b6d8-42cf-887d-2c3e7a0da60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @id = 'pgProcedureList_Filter1_1' and @name = 'pgProcedureList_Filter1_1' and @alt = 'pgProcedureList_Filter1_1']</value>
      <webElementGuid>972bfc9f-2f7c-4d34-8951-b40bcfde2174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
