<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Procedure Code_pgProcedureList_Grid1__28c48d</name>
   <tag></tag>
   <elementGuidId>58754c83-8ba0-4573-bc36-5b5b16470263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgProcedureList_Grid1_GoButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pgProcedureList_Grid1_GoButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e55936e9-f2e7-45d4-be1f-5d9b48ac1fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>BUTTON</value>
      <webElementGuid>24a4b34b-6345-4601-b71a-f29bfe0e2e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgProcedureList_Grid1_GoButton</value>
      <webElementGuid>955e9a26-f6b4-4e6d-9055-7fd9385c6d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgProcedureList_Grid1_GoButton</value>
      <webElementGuid>0bf633ee-4c30-4bc1-bf03-a25ca1ced9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>8ba64606-cbd3-46db-a9a8-338ef31b3ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f1b39160-80ee-465f-a863-56ed13578d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>goButton('/S2bZCZOwGW4xWSHAbJitPDAN3CjOcUoHcKd8mBrVCFEUpWOQQBAMZHnIAa6UbhOqrj0kdSnC3ZvX5FJ8Kp71jp1rNQyRfVFXaAk+OyQUuiagrz24Ir8lJKmXggCXXf00TKMiKPyUqY4DcRi2+ae/RZFBoZ7mjaQx','pgProcedureList_Grid1');</value>
      <webElementGuid>9ca7eea7-30a4-4efc-8597-660af3aefcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibtn i-icon i-icon-play-circle </value>
      <webElementGuid>74570a27-7904-41ec-84c5-a8d49541182f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg</name>
      <type>Main</type>
      <value>NOT-DEFINED-PGC</value>
      <webElementGuid>c1572a54-5994-4344-a062-d4e9e9529851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Procedure Code  Filter Go</value>
      <webElementGuid>86ac4d27-722e-403e-99b4-8783e01ebd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Procedure Code  filter Go </value>
      <webElementGuid>8d605d87-ba56-4986-ba30-aae3db7bd4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgProcedureList_Grid1_GoButton&quot;)</value>
      <webElementGuid>bee40d39-4bdb-410e-bb78-06a41bd80e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pgProcedureList_Grid1_GoButton']</value>
      <webElementGuid>b3cc134b-5f53-4a76-ac47-90599ef76017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgProcedureList_Grid1_filter']/div[10]/input</value>
      <webElementGuid>dff1c849-b291-47d6-97d6-56f8e785bd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>3884c978-5088-4131-b449-f74408aad529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'BUTTON' and @id = 'pgProcedureList_Grid1_GoButton' and @name = 'pgProcedureList_Grid1_GoButton' and @title = 'Procedure Code  Filter Go']</value>
      <webElementGuid>7c6d597a-00eb-484b-8d17-4d3596a9f89f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
